---
title: "Historic_pike_analysis"
author: "TR"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(data.table)
library(readxl)
library(scales)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(khroma)
library(RColorBrewer)
library(flextable)
library(MixSIAR)
library(plyr)
library(FSA)
library(terra)
library(maps)
library(sf)
library(emmeans)
library(segmented)
library(strucchange)
library(brms)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

# Data cleaning

```{r historic data, include=FALSE, eval=FALSE}
rm(list = ls())

#To be replaced once pike are in database
Pike_loc <- fread("Data/Pike/Pike_Zuordnung_Bodden.CSV")

Pike1 <- Pike_loc%>%
  transmute(Oldenburg_ID = paste0(Tuete, ".", Stapel, ".", Tuetchen),
            Capture_location_cor = Kernbodden_korrigiert)%>%
  distinct()

#ID as given
Pike_ID <- fread("Data/Pike/Historic_pike_raw.CSV")

Pike2 <- Pike_ID%>%
  left_join(Pike1, by = "Oldenburg_ID")%>%
  mutate(Capture_location = case_when(Capture_location_cor == "Nordr\xfcgener Bodden" ~ "NRB",
                                      Capture_location_cor == "Barther Bodden" ~ "BAT",
                                      Capture_location_cor == "Greifswalder Bodden" ~ "GB",
                                      Capture_location_cor == "Peenestrom" ~ "P",
                                      Capture_location_cor == "Saaler Bodden" ~ "SAB",
                                      Capture_location_cor == "Strelasund" ~ "S",
                                      Capture_location_cor == "" ~ "U",
                                      Fish_ID == "BH-80002" ~ "GB",
                                      Fish_ID == "BH-80163" ~ "P",
                                      Fish_ID == "BH-80164" ~ "P",
                                      Fish_ID == "BH-80166" ~ "GB",
                                      Fish_ID == "BH-80167" ~ "GB"))%>%
  transmute(Fish_ID,
            Date = lubridate::date(parse_date_time(Date, "dmy")),
            Waterbody = Capture_location,
            Total_Length_mm = Total_Length_mm/10,
            Sex,
            Weight = Weight_g,
            Oldenburg_ID)

fwrite(Pike2, "Data/Pike/Historic_pike_master.csv")
```

```{r join to recent database, include=FALSE, eval=FALSE}
Pike1 <- readRDS("D:/Nextcloud IGB/Boddenhecht/Data/Pike Data/1.pike_data_base_FOR_USERS/1Pike_Latest_Version.rds")
PikeH <- fread("Data/Pike/Historic_pike_master.csv")
PikeH$Row_ID <- ((max(Pike1$Row_ID)+1):(max(Pike1$Row_ID)+nrow(PikeH)))

str(Pike1)
str(PikeH)

PikeH2 <- PikeH%>%
  reframe(Row_ID, Fish_ID,
          Date = as.character(Date),
          Total_Length_mm = as.integer(Total_Length_mm*10),
          Weight = as.numeric(Weight),
          Sex, Waterbody, Oldenburg_ID,
          Sample_Origin = "Historic_Winkler_Samples")

Pike2 <- plyr::rbind.fill(Pike1, PikeH2)

saveRDS(Pike2, "D:/Nextcloud IGB/Boddenhecht/Data/Pike Data/1.pike_data_base_FOR_USERS/1Pike_Latest_Version.rds")
fwrite(Pike2, "D:/Nextcloud IGB/Boddenhecht/Data/Pike Data/1.pike_data_base_FOR_USERS/1Pike_Latest_Version.txt")
```

```{r join with genotypes, include=FALSE, eval=FALSE}
rm(list = ls())

substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x)-1)
}

#Load STRUCTURE output file
geneticsdata <- read.delim("Data/Pike/struct_K5_1_f_GTinfo_historic.txt", sep = "", dec = ".", header = F, stringsAsFactors = F)

#prefilter
geneticsdata2 <- geneticsdata%>%
  filter(!str_detect(V1, "BH")&str_detect(V1, "_"))

#Replace P, S and U with double letters
geneticsdata2$V7 <- gsub(pattern = "[^0-9.-]", replacement = '', geneticsdata2$V1)

geneticsdata2 <- geneticsdata2%>%
  mutate(V8 = paste0(substr(V7, 1, 1), ".", substr(V7, 2, 2), ".", substr(V7, 3, 20)))

#Genotypes: 1 = brackish 1; 1 = brackish 2; 3 = freshwater/anadromous; 2 = brackish 3; 4 = freshwater
Genotypes <- geneticsdata2%>%
  transmute(Oldenburg_ID = V8,
            cluster1 = as.numeric(V2)+as.numeric(V3),
            cluster2 = as.numeric(V5),
            cluster3 = as.numeric(V4),
            cluster4 = as.numeric(V6))%>%
  drop_na()

#Missing from Genos: 3.3.27 (geno no, molsex yes? also 3.3.43, other way round for 3.3.10) - 3.3.39; 3.3.1 - 3.3.6; 3.3.12, 3.3.14; 3.3.40; 3.3.41; 3.3.46, everything 3.1.
#3.2.154; 3.2.132; 3.3.158; 3.3.159; 3.2.145; 3.2.23; 3.2.29; 3.2.113; 3.2.37; 3.2.43; 3.2.82;
#3.2.107; 3.2.96; 3.2.1; 4.1.205; 4.1.203; 4.1.195; 4.1.193; 4.1.13; 4.1.185; 4.1.208; 4.1.101; 4.1.92
#4.1.51; 4.1.188; 4.1.140; 4.1.163; 4.1.161

Genotypes$clust <- apply(Genotypes[,c(2,3,4,5)], 1, FUN = which.max)
Genotypes$clustval <- apply(Genotypes[,c(2,3,4,5)], 1, FUN = max)

Genotypes2 <- Genotypes%>%
  mutate(Genotype = case_when(clustval < 0.5 ~ "0",
                            TRUE~as.character(clust)))


Genotypes2$Genotype <- fct_relevel(Genotypes2$Genotype, "4", "3", "1", "2", "0")

Genotypes3 <- Genotypes2%>%
  transmute(Oldenburg_ID, Genotype,
            Old_ID2 = Oldenburg_ID)

#Load pike data
Pikedata <- fread("Data/Pike/Historic_pike_master.csv")

Pikedata2 <- Pikedata%>%
  left_join(Genotypes3, by = "Oldenburg_ID")%>%
  transmute(Fish_ID, Date, Waterbody, Total_Length_mm, Sex, Weight, Oldenburg_ID, Old_ID2, Genotype)

Pikedata3 <- Genotypes3 %>%
  left_join(Pikedata, by = "Oldenburg_ID")%>%
  transmute(Oldenburg_ID, Old_ID2, Fish_ID)

#Problem: No 1.anything, or 2.anything

fwrite(Pikedata2, "Data/Pike/Historic_pike_master.csv")
```

```{r Cleanup scale data, include=FALSE, eval=FALSE}
rm(list = ls())

Scaleread <- fread("Data/Pike/Pike-scales-main-run.csv")
Scaleread_add <- fread("Data/Pike/Addition.csv")
Scaleread_addadd <- fread("Data/Pike/Addition2.csv")
Decoder <- fread("Data/Pike/Decoding_file_Scales-historic-vs-recent_all.csv")
Addendum_pike <- fread("Data/Pike/Historic_raw_2.csv")

Decoder2 <- Decoder %>%
  filter(!(as.integer(substr(fish_ID, 4, 8)) >= 80000 & as.integer(substr(fish_ID, 4, 8)) < 90000 & year(capt_date) > 2020))

Scaleread2 <- Scaleread%>%
  filter(Quality > 0) %>%
  transmute(random_ID = Sample,
            quality = Quality,
            age = Age,
            cohort = Cohort,
            pisc = Piscivorous,
            I = I,
            year = Year,
            increment = Increment)

Decoder2$random_ID <- as.integer(gsub(".jpg", "", Decoder2$random_ID))

Pikeages <- Scaleread2%>%
  left_join(Decoder2, by = "random_ID")%>%
  distinct()

Scaleread_add2 <- Scaleread_add %>%
  filter(Quality > 0) %>%
  transmute(fish_ID = substr(Sample, 1,8),
            quality = Quality,
            age = Age,
            cohort = Cohort,
            pisc = Piscivorous,
            I = I,
            year = Year,
            increment = Increment)

Pikeages_add <- Scaleread_add2 %>%
  left_join(Decoder2, by = "fish_ID")%>%
  distinct()

Scaleread_addadd2 <- Scaleread_addadd %>%
  filter(Quality > 0) %>%
  transmute(Fish_ID = substr(Sample, 26,33),
            quality = Quality,
            age = Age,
            cohort = Cohort,
            pisc = Piscivorous,
            I = I,
            year = Year,
            increment = Increment)

Pikeages_add2 <- Scaleread_addadd2 %>%
  left_join(Addendum_pike, by = "Fish_ID") %>%
  transmute(fish_ID = Fish_ID,
            quality, age, cohort, pisc, I, year, increment,
            file_name = NA,
            capt_date = as.IDate(parse_date_time(Date, "dmy")),
            TL_mm = Total_Length_mm,
            weight = Weight_g,
            sex = Sex,
            area = Capture_location,
            random_ID = NA)

Pikeages <- rbind(Pikeages, Pikeages_add, Pikeages_add2)

#remove suspicious (Wrong ID, double ID, etc.) individuals

Pikeages2 <- Pikeages%>%
  filter(!fish_ID %in% c("BH-90793", "BH-90017", "BH-91890", "BH-91748", "BH-90009", "BH-91620", "BH-91929", "BH-91644", "BH-00683", "BH-91882",
                         "BH-91810", "BH-91131", "BH-91626", "BH-00674", "BH-91839"))%>%
  filter(!random_ID %in% c(362, 3821)) %>%
  transmute(fish_ID, TL_mm, age, cohort, weight, sex, area, capt_date, I, year, increment, pisc, quality, file_name, random_ID)

ggplot(Pikeages2[Pikeages2$quality == 3,], aes(as.factor(age), TL_mm))+
  geom_point(aes(color = sex))+
  theme_minimal()

Pikeages3 <- Pikeages2%>%
  group_by(fish_ID)%>%
  dplyr::summarise(fish_ID=fish_ID,
            age=median(age, na.rm = T))%>%
  distinct()

length(unique(Pikeages3$fish_ID))

Pikeages_final <- Pikeages2 %>%
  filter(quality > 0) %>%
  inner_join(Pikeages3, by = c("fish_ID", "age"))%>%
  group_by(fish_ID, I)%>%
  filter(I != "Piscivorous")%>%
  mutate(capt_date = case_when(is.na(capt_date) ~ as.IDate("2020-01-01"),
                                     TRUE ~ capt_date))%>%
  transmute(fish_ID, TL_mm, 
            age = case_when(month(capt_date) < 5 & month(capt_date) >= 1 ~ age + 1,
                            TRUE ~ age), 
            cohort = year(capt_date)-age,
            weight, sex, area, capt_date,
            I = case_when(I == "edge" & month(capt_date) < 5 & month(capt_date) >= 1 ~ "edgeyear",
                          TRUE ~ I),
            year = year,
            increment = mean(increment), 
            pisc = mean(pisc))%>%
  drop_na(fish_ID)%>%
  distinct()

length(unique(Pikeages_final$fish_ID))

Pikeages_final <- as.data.frame(Pikeages_final)

IDpike <- unique(Pikeages_final$fish_ID)
rad <- NULL
for (i in 1:length(IDpike)) {
  d <- cumsum(coalesce(Pikeages_final[which(Pikeages_final$fish_ID == IDpike[i]), "increment"], 0)) +
    Pikeages_final[which(Pikeages_final$fish_ID == IDpike[i]), "increment"]*0
  
  rad <- c(rad, d)
}

Pikeages_final$rad <- rad

Pikeages_final2 <- Pikeages_final %>%
  ungroup() %>%
  group_by(fish_ID) %>%
  dplyr::mutate(scale_width = max(rad)) %>%
  filter(I != "edge") %>%
  mutate(I = case_when(I == "edgeyear" ~ age,
                              TRUE ~ as.numeric(I)))%>%
  transmute(fish_ID, TL_mm, age, cohort, weight, sex, area, capt_date,
            lifeyear = I,
            year = year(capt_date)-age+lifeyear,
            increment, 
            radius = rad, 
            scale_width, pisc)

#Convert pixel values into micrometers

#Retrieve readers
Fritz_scales <- fread("Data/Pike/Fritz_pike_scales_all_with_rad_checked.txt")
Nico_scales <- fread("Data/Pike/Nico_scales_all_with_rad_checked.txt")

Fritz2 <- Fritz_scales %>% transmute(fish_ID, imaging = "Marlon") %>% distinct()
Nico2 <- Nico_scales %>% transmute(fish_ID, imaging = "Nico") %>% distinct()

Fritznico <- rbind(Fritz2, Nico2)

Pike_readers <- Pikeages2 %>% left_join(Fritznico, by = "fish_ID")

Pike_readers2 <- Pike_readers %>%
  transmute(fish_ID, capt_date, area, file_name, random_ID,
            imaging = case_when(is.na(imaging) == TRUE ~ "Timo",
                                year(capt_date) < 2000 ~ "Timo",
                                TRUE ~ imaging)) %>%
  distinct()

# BH-00112 - BH-00753 scale = 0.1758 px / um
# Nico BAT, SB, KB, GB, Sehrowbach 2021, Barthe, BAT 2021, BEG, Beek, P, Peene, Strelasund, Duwenbeek scale = 0.19175 px / um
# Nico Sehrowbach 2020 scale = 0.1898 px / um
# Timo recent, historic scale = 0.1935 px / um
# Marlon SBKB Summer, SBKB spring, SBKB fall, GB fall, GB spring, GB summer, BAT spring, BAT summer, BAT fall scale = 0.1898 px / um
# Marlon mixed pics scale = 0.1896 px / um

Pike_scales_scale <- Pike_readers2 %>%
  mutate(scale = case_when(as.integer(substr(fish_ID, 4, 8)) < 1000 ~ 0.1758,
                           imaging == "Timo" ~ 0.1935,
                           imaging == "Nico" & area != "Sehrowbach" ~ 0.19175,
                           imaging == "Nico" & year(capt_date) < 2021 & area == "Sehrowbach" ~ 0.1898,
                           imaging == "Nico" & year(capt_date) > 2020 & area == "Sehrowbach" ~ 0.19175,
                           imaging == "Marlon" ~ 0.1897)) %>%
  transmute(fish_ID, scale, imaging) %>%
  distinct()

Pikeages_final3 <- Pikeages_final2 %>%
  left_join(Pike_scales_scale, by = "fish_ID")%>%
  transmute(fish_ID, TL_mm, age, cohort, weight, sex, area, capt_date,lifeyear, year,
            increment_mm = increment/scale/1000,
            radius_mm = radius/scale/1000, 
            scale_width_mm = scale_width/scale/1000,
            pisc_mm = pisc/scale/1000,
            scale, imaging)

Pikemaster <- fread("Data/Pike/Historic_pike_master.csv")

Pikemaster2 <- Pikemaster %>%
  transmute(fish_ID = Fish_ID, Oldenburg_ID, Genotype)

Pikemaster3 <- Pikeages_final3 %>%
  left_join(Pikemaster2, by = "fish_ID")%>%
  ungroup() %>%
  transmute(Fish_ID = fish_ID,
            TL_mm,
            Sample = case_when(year(capt_date) < 2000 ~ "Historic",
                               TRUE ~ "Recent"),
            Age = age,
            Cohort = cohort,
            Weight = weight,
            Sex = sex,
            Area = area,
            Capt_date = capt_date,
            Lifeyear = lifeyear,
            Year = year,
            Increment_mm = increment_mm,
            Radius_mm = radius_mm,
            Scale_width_mm = scale_width_mm,
            Pisc_mm = pisc_mm,
            Scale = scale,
            Imaging = imaging,
            Oldenburg_ID, 
            Genotype = as.factor(Genotype)) %>%
  distinct()

ggplot(Pikemaster3, aes(as.factor(Age), TL_mm))+
  geom_point(aes(color = Sample))+
  theme_minimal()

ggplot(Pikeages_final3[Pikeages_final3$age<2,], aes(scale_width_mm, TL_mm))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()
  
summary(lm(TL_mm ~ scale_width_mm, data = Pikeages_final3[Pikeages_final3$age<2,]))

Pikemaster4 <- Pikemaster3 %>%
  group_by(Fish_ID) %>%
  mutate(Length_back = Radius_mm/Scale_width_mm*TL_mm)%>%
  mutate(Pisc_mm = Pisc_mm/Scale_width_mm*TL_mm) %>%
  dplyr::mutate(Length_LI = max(Length_back)) %>%
  ungroup() %>%
  distinct()

Otopike <- fread("Data/Pike/Otolith-ages-TL.csv")

Otopike2 <- Otopike %>%
  group_by(ID) %>%
  dplyr::mutate(Length_back = rad_um/total_rad_um*TL_mm,
                Length_LI = max(Length_back)) %>%
  ungroup() %>%
  transmute(Fish_ID = ID,
            TL_mm,
            Sample = "Recent",
            Age = age,
            Cohort = cohort,
            Weight = weight_g,
            Sex = sex,
            Area = capt,
            Capt_date = date,
            Lifeyear = lifeyear,
            Year = year,
            Increment_mm = increment_um/10,
            Radius_mm = rad_um/10,
            Scale_width_mm = total_rad_um/10,
            Length_back, Length_LI)

Pikemaster5 <- rbind.fill(Pikemaster4, Otopike2)

#join genotypes
#Load STRUCTURE output file
geneticsdata <- read.delim("Data/Pike/struct_K5_1_f_GTinfo_historic.txt", sep = "", dec = ".", header = F, stringsAsFactors = F)

substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

#prefilter
geneticsdata2 <- geneticsdata%>%
  filter(str_detect(V1, "BH"))

#Genotypes: 1 = brackish 1; 2 = brackish 2; 3 = freshwater/anadromous; 4 = freshwater
Genotypes <- geneticsdata2%>%
  transmute(ID=paste0(sub("_","-",str_extract(V1, "BH_\\d{5}"))),
            cluster1 = as.numeric(V2)+as.numeric(V3),
            cluster2 = as.numeric(V5),
            cluster3 = as.numeric(V4),
            cluster4 = as.numeric(V6))%>%
  drop_na()


Genotypes$clust <- apply(Genotypes[,c(2,3,4,5)], 1, FUN = which.max)
Genotypes$clustval <- apply(Genotypes[,c(2,3,4,5)], 1, FUN = max)

Genotypes2 <- Genotypes%>%
  mutate(Genotype = case_when(clustval < 0.5 ~ "0",
                            TRUE~as.character(clust)))

Genotypes2$Genotype <- fct_relevel(Genotypes2$Genotype, "4", "3", "1", "2", "0")

Genotypes3 <- Genotypes2%>%
  transmute(Fish_ID = ID, Genotype2 = Genotype)

Pikemaster6 <- Pikemaster5 %>%
  filter(Area != "KD") %>%
  left_join(Genotypes3, by = "Fish_ID")%>%
  mutate(Genotype = case_when(is.na(Genotype) == TRUE ~ Genotype2,
                              TRUE ~ Genotype))%>%
  filter(Length_back > 0)


fwrite(Pikemaster6, "Data/Pike/Pikemaster.csv")
```

```{r genotype frequencies historic vs present, include=FALSE, eval=FALSE}
rm(list = ls())

# --- Genotyp-Häufigkeiten nach Sample (Historic/Recent) ---
Pikemaster <- fread("Data/Pike/Pikemaster.csv")

genotype_labels <- c(
  "1" = "Brackish 1",
  "2" = "Brackish 2",
  "3" = "Freshwater/anadromous",
  "4" = "Freshwater",
  "0" = "Not assigned"
)

genotype_colors <- c(
  "Brackish 1"             = "#004643",
  "Brackish 2"             = "#F1C40F",
  "Freshwater/anadromous"  = "#00BFB2",
  "Freshwater"             = "#C5D86D",
  "Not assigned"           = "grey2"
)

Genotype_freq <- Pikemaster %>%
  dplyr::filter(!is.na(Genotype), !is.na(Sample)) %>%
  dplyr::mutate(Genotype_label = dplyr::recode(as.character(Genotype), !!!genotype_labels),
                Genotype_label = factor(Genotype_label, levels = names(genotype_colors))) %>%
  dplyr::count(Sample, Genotype_label, name = "n", .drop = FALSE) %>%
  dplyr::group_by(Sample) %>%
  dplyr::mutate(Proportion = n / sum(n)) %>%
  dplyr::arrange(Sample, Genotype_label) %>%
  dplyr::mutate(csum = rev(cumsum(rev(Proportion))),
                pos1 = Proportion / 2 + dplyr::lead(csum, 1),
                pos = dplyr::case_when(is.na(pos1) ~ Proportion / 2, TRUE ~ pos1)) %>%
  dplyr::ungroup()

GenotypePlot <- ggplot(Genotype_freq, aes(x = "", y = Proportion, fill = Genotype_label)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_label_repel(aes(y = pos, label = scales::percent(Proportion, accuracy = 0.1)),
                    nudge_x = 0.6, size = 2.5, show.legend = FALSE, fill = "white") +
  facet_wrap(~ Sample) +
  scale_fill_manual(values = genotype_colors, name = "Genotype") +
  theme_void() +
  theme(legend.position = "bottom",
        strip.text = element_text(size = 15, colour = "black"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10))

ggsave("Figures/Genotype_frequencies.png", GenotypePlot, width = 16, height = 10, units = "cm", dpi = 600, bg = "white")

Genotype_table <- Pikemaster %>%
  dplyr::filter(!is.na(Genotype), !is.na(Sample)) %>%
  dplyr::mutate(Genotype_label = dplyr::recode(as.character(Genotype), !!!genotype_labels),
                Genotype_label = factor(Genotype_label, levels = names(genotype_colors))) %>%
  dplyr::filter(Genotype_label != "Freshwater") %>%
  dplyr::mutate(Genotype_label = forcats::fct_drop(Genotype_label)) %>%
  dplyr::count(Sample, Genotype_label, name = "n", .drop = FALSE) %>%
  tidyr::pivot_wider(names_from = Genotype_label, values_from = n, values_fill = 0) %>%
  tibble::column_to_rownames("Sample") %>%
  as.matrix()

Genotype_table

chisq_genotype <- chisq.test(Genotype_table)
chisq_genotype

chisq_genotype$expected

chisq_genotype$stdres
```


```{r join age readings with isotope data, include=FALSE, eval=FALSE}
#Create overview list of pike for which SI data and scale readings exist to identify fish that need SI reading
#Script uses already processed data, will change when data is run through final data check of MS 3

rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
#Complete isotope dataset
Isopike <- fread("Data/Pike/Pike_SI_all_clean_average_lipid-corrected.csv")
Isopike$Fish_ID <- Isopike$ID


#Filter for pike with complete isotope measurements
Isopike2 <- Isopike%>%
  transmute(Fish_ID = Fish_ID,
            d15N_muscle = d15N,
            d13C_muscle = d13C,
            d34S_muscle = d34S) %>%
  distinct()

Pikemaster2 <- Pikemaster %>%
  left_join(Isopike2, by = "Fish_ID")%>%
  dplyr::select(!Genotype2)

#join genotypes
#Load STRUCTURE output file
geneticsdata <- read.delim("Data/Pike/struct_K5_1_f_GTinfo_historic.txt", sep = "", dec = ".", header = F, stringsAsFactors = F)

substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

#prefilter
geneticsdata2 <- geneticsdata%>%
  filter(str_detect(V1, "BH"))

#Genotypes: 1 = brackish 1; 2 = brackish 2; 3 = freshwater/anadromous; 4 = freshwater
Genotypes <- geneticsdata2%>%
  transmute(ID=paste0(sub("_","-",substrRight(V1,8))),
            cluster1 = as.numeric(V2)+as.numeric(V3),
            cluster2 = as.numeric(V5),
            cluster3 = as.numeric(V4),
            cluster4 = as.numeric(V6))%>%
  drop_na()


Genotypes$clust <- apply(Genotypes[,c(2,3,4,5)], 1, FUN = which.max)
Genotypes$clustval <- apply(Genotypes[,c(2,3,4,5)], 1, FUN = max)

Genotypes2 <- Genotypes%>%
  mutate(Genotype = case_when(clustval < 0.5 ~ "0",
                            TRUE~as.character(clust)))

Genotypes2$Genotype <- fct_relevel(Genotypes2$Genotype, "4", "3", "1", "2", "0")

Genotypes3 <- Genotypes2%>%
  transmute(Fish_ID = ID, Genotype = Genotype)

Isopike3 <- Isopike %>%
  left_join(Genotypes3, by = "Fish_ID")

Isoadd <- Isopike3 %>%
  filter(!Fish_ID %in% c(Pikemaster$Fish_ID))%>%
  transmute(Fish_ID, TL_mm,
            Sample = "Recent",
            Age = NA,
            Cohort = NA,
            Weight = weight_g,
            Sex = sex,
            Area = area,
            Capt_date = capt_date,
            Lifeyear = NA,
            Year = NA,
            Increment_mm = NA,
            Radius_mm = NA,
            Scale_width_mm = NA,
            Pisc_mm = NA,
            Scale = NA,
            Imaging = NA,
            Oldenburg_ID = NA,
            Genotype,
            Length_back = NA,
            Length_LI = NA,
            d15N_muscle = d15N,
            d13C_muscle = d13C,
            d34S_muscle = d34S)

Pikemaster3 <- rbind(Pikemaster2, Isoadd)

#Join scale isotopes
Isoall <- fread("Data/Pike/2024-06-21_NCS_TRittweg_Results.CSV")

Isoscales <- Isoall %>%
  filter(Identifier_1 == "scale")%>%
  transmute(Fish_ID = case_when(startsWith(Identifier_2, "BH") ~ paste0(substr(Identifier_2, 1,2), "-", substr(Identifier_2, 3,7)),
                             TRUE ~ Identifier_2),
            d13C_scale = as.numeric(`d13C/12C_Calculated`),
            d15N_scale = as.numeric(`d15N/14N_Calculated`),
            d34S_scale = as.numeric(`d34S/32S_Calculated`),
            CN_ratio = as.numeric(Cperc)/as.numeric(Nperc))

#join with other scale isotopes

Scales0 <- fread("Data/Pike/2024-01-25_NCS_Pike-scales.CSV")
Scales1 <- Scales0 %>%
  transmute(Fish_ID = paste0(substr(V3, 1,2), "-", substr(V3, 3,7)),
            d13C_scale = as.numeric(V7),
            d15N_scale = as.numeric(V5),
            d34S_scale = as.numeric(V9),
            CN_ratio = as.numeric(V8)/as.numeric(V6))

Isoscales2 <- rbind(Isoscales, Scales1)

ggplot(data = Isoscales2, aes(CN_ratio, d13C_scale))+
  geom_smooth(method = "lm")+
  geom_point()+
  theme_bw()

Isoscales3 <- Isoscales2 %>%
  group_by(Fish_ID) %>%
  reframe(Fish_ID,
                   d13C_scale = mean(d13C_scale),
                   d15N_scale = mean(d15N_scale),
                   d34S_scale = mean(d34S_scale)) %>%
  ungroup() %>%
  distinct()

#Join with pikemaster
Pikemaster4 <- Pikemaster3 %>%
  left_join(Isoscales3, by = "Fish_ID")%>%
  distinct()

#Check missing fish
Isoscales_check <- Isoscales3 %>%
  filter(startsWith(Fish_ID, "BH-80")) %>%
  distinct()

Pikecheck <- Pikemaster2 %>%
  filter(startsWith(Fish_ID, "BH-80"))%>%
  transmute(Fish_ID,
            Fish_ID2 = Fish_ID)

Isocheck <- Isoscales_check %>%
  left_join(Pikecheck, by = "Fish_ID") %>%
  distinct() %>%
  filter(is.na(Fish_ID2) == TRUE)

#Adjoin missing fish
Histopike <- fread("Data/Pike/Historic_pike_master.csv")

Histo_iso_add <- Histopike %>%
  left_join(Isocheck, by = "Fish_ID")%>%
  drop_na(d34S_scale)%>%
  transmute(Fish_ID, 
            TL_mm = Total_Length_mm,
            Sample = "Historic",
            Capt_date = Date,
            Sex,
            Area = Waterbody,
            Weight, Genotype, d13C_scale, d15N_scale, d34S_scale)

Pikemaster5 <- plyr::rbind.fill(Pikemaster4, Histo_iso_add)

#fwrite(Pikemaster5, "Data/Pike/Pikemaster.csv")

Pikemaster6 <- Pikemaster %>%
  transmute(Fish_ID, Sample, Area)%>%
  distinct()

table(Pikemaster6[Pikemaster6$Sample == "Recent",]$Area)
```

# Growth analysis
## von Bertalanffy growth curves

```{r Size at age descriptive, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
Sexpike <- fread("Data/Pike/molsexed_pike_historic.csv")

Sexpike2 <- Sexpike %>%
  transmute(Oldenburg_ID = Fish_ID, 
            Sex_molecular = Sex_Updated) %>%
  distinct()

Pikemaster$Oldenburg_ID <- gsub("\\.", "-", Pikemaster$Oldenburg_ID)

#check length of historic pike before join
length(unique(Pikemaster[Pikemaster$Sample == "Historic",]$Fish_ID))

Pikemaster2 <- Pikemaster %>%
  left_join(Sexpike2, by = "Oldenburg_ID")


Pikemaster3 <- Pikemaster2 %>%
  filter(is.na(Age) == FALSE) %>%
  mutate(Sex = case_when(Sex == ""|is.na(Sex) == TRUE ~ Sex_molecular,
                         TRUE ~ Sex),
         Sample = paste0(Sample, "-", Sex)) %>%
  filter(Sex == "f"|Sex == "m")

#check length again
length(unique(Pikemaster3[Pikemaster3$Sample == "Historic-f",]$Fish_ID))+
  length(unique(Pikemaster3[Pikemaster3$Sample == "Historic-m",]$Fish_ID))

fwrite(Pikemaster3, "Data/Pike/Pikemaster_sex.csv")

Growthtable <- Pikemaster3 %>%
  transmute(Fish_ID, Capt_date, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Sample = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek") ~ "Freshwater",
                            TRUE ~ Sample),
         Sample_bin = case_when(Sample == "Recent-f" ~ 1,
                                Sample == "Recent-m" ~ 2,
                                Sample == "Historic-f" ~ 3,
                                Sample == "Historic-m" ~ 4,
                                TRUE ~ 5)) %>%
  filter(is.na(Age) != TRUE, Sample != "Freshwater") %>%
  distinct()

Meansize_hist <- Growthtable %>%
  filter(year(Capt_date) < 2000 & Age <= 10) %>%
  group_by(Age) %>%
  reframe(
    Decade = "Historic",
    Mean_length = mean(Length_LI, na.rm = TRUE),
    SDlength = sd(Length_LI, na.rm = TRUE),
    N = n())

Meansize_rec <- Growthtable %>%
  filter(year(Capt_date) > 2000 & Age <= 10) %>%
  group_by(Age) %>%
  reframe(
    Decade = "Recent",
    Mean_length = mean(Length_LI, na.rm = TRUE),
    SDlength = sd(Length_LI, na.rm = TRUE),
    N = n())

Mean_size_at_age <- rbind(Meansize_hist, Meansize_rec)

df <- Mean_size_at_age %>%
  pivot_wider(names_from = Decade,
              values_from = c(Mean_length, SDlength, N),
              names_glue = "{.value}_{Decade}")

df_ft <- data.frame(Age = df$Age,
                    Historic_mean_sd = sprintf("%.1f ± %.1f", df$Mean_length_Historic/10, df$SDlength_Historic/10),
                    Historic_n = df$N_Historic,
                    Recent_mean_sd = sprintf("%.1f ± %.1f", df$Mean_length_Recent/10, df$SDlength_Recent/10),
                    Recent_n = df$N_Recent)

ft <- flextable(df_ft) %>%
  set_header_labels(Age = "Age",
                    Historic_mean_sd = "Mean length ± SD",
                    Historic_n = "n",
                    Recent_mean_sd = "Mean length ± SD",
                    Recent_n = "n") %>%
  add_header_row(values = c("", "Historic", "Recent"),
                 colwidths = c(1, 2, 2)) %>%
  flextable::align(j = 2:5, align = "center", part = "all") %>%
  flextable::bold(part = "header") %>%
  flextable::theme_booktabs() %>%
  flextable::autofit()

ft

save_as_docx(ft, path = "Figures/Age-at-length_table.docx")
```

```{r Von Bertalanffy historic vs recent, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster3 <- fread("Data/Pike/Pikemaster_sex.csv")
priors <- fread("Data/Pike/Priors_pike.csv")

#Check sample size, historic (last updated 26-02-26) should be 542

length(unique(Pikemaster3[Pikemaster3$Sample == "Historic-f",]$Fish_ID))+
  length(unique(Pikemaster3[Pikemaster3$Sample == "Historic-m",]$Fish_ID))

Growthtable <- Pikemaster3 %>%
  transmute(Fish_ID, Capt_date, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Sample = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek", "Badendycksgraben", "Barthe/Peene") ~ "Freshwater",
                            TRUE ~ Sample),
         Sample_bin = case_when(Sample == "Recent-f" ~ 1,
                                Sample == "Recent-m" ~ 2,
                                Sample == "Historic-f" ~ 3,
                                Sample == "Historic-m" ~ 4,
                                TRUE ~ 5)) %>%
  filter(is.na(Age) != TRUE) %>%
  distinct()

#check sample size again, should be 535 for historic (last updated 26-02-26) due to missing ages

length(unique(Growthtable[Growthtable$Sample == "Historic-f",]$Fish_ID))+
  length(unique(Growthtable[Growthtable$Sample == "Historic-m",]$Fish_ID))

standata_Pike1 = list(
  Length = Growthtable$Length_LI/10,
  Age = Growthtable$Age,
  N = nrow(Growthtable),
  Sample = Growthtable$Sample_bin,
  linf_mean = mean(priors$Loo), #alt: mean^2/variance & variance/mean
  linf_var = sd(priors$Loo),
  t0_mean = mean(priors$to),
  t0_var = sd(priors$to)^2,
  k_prior = 1,  
  n_groupmax = as.integer(max(length(Growthtable[Growthtable$Sample_bin == 1,]$Fish_ID))),
  n_areas = as.integer(max(Growthtable$Sample_bin)),
  Area_id = Growthtable$Sample_bin
)

# Modelling
stancode <- "Data/Pike/Stan/Simple_VBGF_TZero_historic-vs-recent-vs-freshwater.stan"

mod = stan_model(stancode, model_name = "pike growth population")

#fitting
fit_1 = sampling(mod, iter = 40000, data = standata_Pike1, thin = 100,
                   control = list(adapt_delta = 0.95, max_treedepth = 14))

print(fit_1, pars = c("LInf_area[1]", "LInf_area[2]", "LInf_area[3]", "LInf_area[4]", "LInf_area[5]"))

saveRDS(fit_1, "Data/Pike/Stan/Model-recent-vs-historic_complex.rds")

p = c("LInf_area", "tZero_area", "k_area")

samps = as.matrix(fit_1, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)
```

```{r Von Bertalanffy area-specific, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")

Growthtable <- Pikemaster %>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Area = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek", "NHG", "Badendycksgraben", "Ziese", "Barthe/Peene") ~ "Tributary",
                          Area %in% c("NRB", "BAT", "GB", "S", "SB", "U", "KB", "WB", "BEG", "BEZ", "GJB", "VB") ~ "Mesohaline",
                          Area %in% c("P", "KJB", "SAB", "DZB") ~ "Oligohaline",
                          TRUE ~ Area),
         Sample_bin = case_when(Sample == "Recent" & Area == "Mesohaline" ~ 1,
                                Sample == "Recent" & Area == "Oligohaline" ~ 2,
                                Sample == "Recent" & Area == "Tributary" ~ 3,
                                Sample == "Historic" & Area == "Mesohaline" ~ 4,
                                Sample == "Historic" & Area == "Oligohaline" ~ 5,
                                TRUE ~ 3)) %>%
  distinct()

priors <- fread("Data/Pike/Priors_pike.csv")

standata_Pike2 = list(
  Length = Growthtable$Length_LI/10,
  Age = Growthtable$Age,
  N = nrow(Growthtable),
  Sample = Growthtable$Sample_bin,
  linf_mean = mean(priors$Loo), #alt: mean^2/variance & variance/mean
  linf_var = sd(priors$Loo),
  t0_mean = mean(priors$to),
  t0_var = sd(priors$to)^2,
  k_prior = 1,  
  n_groupmax = as.integer(max(Growthtable %>% group_by(Sample_bin) %>% transmute(sample_num = length(Fish_ID)))),
  n_areas = as.integer(max(Growthtable$Sample_bin)),
  Area_id = Growthtable$Sample_bin
)

# Model
stancode <- "Data/Pike/Stan/Simple_VBGF_TZero_historic-vs-recent-vs-freshwater.stan"

mod = stan_model(stancode, model_name = "pike growth population per area")

#fitting
fit_1 = sampling(mod, iter = 40000, data = standata_Pike2, thin = 100,
                   control = list(adapt_delta = 0.95, max_treedepth = 14))

saveRDS(fit_1, "Data/Pike/Stan/Model-recent-vs-historic_complex_area-specific.rds")

print(fit_1, pars = c("LInf_area", "tZero_area", "k_area", "sigma_area" ))

p = c("LInf_area", "tZero_area", "k_area")

samps = as.matrix(fit_1, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)
```

```{r Von Bertalanffy genotype-specific, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")

#Genotypes: 1 = brackish 1; 2 = brackish 2; 3 = freshwater/anadromous; 4 = freshwater; 0 = unknown
Growthtable <- Pikemaster %>%
  filter(Sample == "Historic")%>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Area = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek", "NHG", "Badendycksgraben", "Ziese", "Barthe/Peene") ~ "Tributary",
                          Area %in% c("NRB", "BAT", "GB", "S", "SB", "U", "KB", "WB", "BEG", "BEZ", "GJB", "VB") ~ "Mesohaline",
                          Area %in% c("P", "KJB", "SAB", "DZB") ~ "Oligohaline",
                          TRUE ~ Area),
         Sample_bin = case_when(Genotype == 1 ~ 1, 
                                Genotype == 2 ~ 2, 
                                Genotype == 3 ~ 3, 
                                Genotype == 4 ~ 4,
                                TRUE ~ 0)) %>%
  distinct()%>%
  drop_na(Genotype, Age)%>%
  filter(Genotype != 0)

priors <- fread("Data/Pike/Priors_pike.csv")

table(Growthtable$Genotype)

standata_Pike3 = list(
  Length = Growthtable$Length_LI/10,
  Age = Growthtable$Age,
  N = nrow(Growthtable),
  Sample = Growthtable$Sample_bin,
  linf_mean = mean(priors$Loo), #alt: mean^2/variance & variance/mean
  linf_var = sd(priors$Loo),
  t0_mean = mean(priors$to),
  t0_var = sd(priors$to)^2,
  k_prior = 1,  
  n_groupmax = as.integer(max(Growthtable %>% group_by(Genotype) %>% transmute(sample_num = length(Fish_ID)))),
  n_geno = as.integer(max(Growthtable$Genotype)),
  geno_id = Growthtable$Genotype
)

# Model
stancode <- "Data/Pike/Stan/Simple_VBGF_TZero_historic-genotypes.stan"

mod = stan_model(stancode, model_name = "pike growth historic genotypes")

#fitting
fit_3 = sampling(mod, iter = 40000, data = standata_Pike3, thin = 100,
                   control = list(adapt_delta = 0.95, max_treedepth = 14))

saveRDS(fit_3, "Data/Pike/Stan/Model_historic-genotypes.rds")

print(fit_3, pars = c("LInf_geno", "tZero_geno", "k_geno", "sigma_geno"))

p = c("LInf_geno", "tZero_geno", "k_geno")

samps = as.matrix(fit_3, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)

Growthtable2 <- Pikemaster %>%
  filter(Sample == "Recent")%>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Area = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek") ~ "Tributary",
                          Area %in% c("NRB", "BAT", "GB", "S", "SB", "U", "KB", "WB", "BEG", "BEZ", "GJB", "VB") ~ "Mesohaline",
                          Area %in% c("P", "KJB", "SAB") ~ "Oligohaline",
                          TRUE ~ Area),
         Sample_bin = case_when(Genotype == 1 ~ 1, 
                                Genotype == 2 ~ 2, 
                                Genotype == 3 ~ 3, 
                                Genotype == 4 ~ 4,
                                TRUE ~ 0)) %>%
  distinct()%>%
  drop_na(Genotype, Age)%>%
  filter(Genotype != 0)

table(Growthtable2$Genotype)

standata_Pike4 = list(
  Length = Growthtable2$Length_LI/10,
  Age = Growthtable2$Age,
  N = nrow(Growthtable2),
  Sample = Growthtable2$Genotype,
  linf_mean = mean(priors$Loo), #alt: mean^2/variance & variance/mean
  linf_var = sd(priors$Loo),
  t0_mean = mean(priors$to),
  t0_var = sd(priors$to)^2,
  k_prior = 1,  
  n_groupmax = as.integer(max(Growthtable2 %>% group_by(Genotype) %>% transmute(sample_num = length(Fish_ID)))),
  n_geno = as.integer(max(Growthtable2$Genotype)),
  geno_id = Growthtable2$Genotype
)

# Model
stancode <- "Data/Pike/Stan/Simple_VBGF_TZero_historic-genotypes.stan"

mod = stan_model(stancode, model_name = "pike growth recent genotypes")

#fitting, run again as you f´d up
fit_4 = sampling(mod, iter = 40000, data = standata_Pike4, thin = 100,
                   control = list(adapt_delta = 0.95, max_treedepth = 14))

saveRDS(fit_4, "Data/Pike/Stan/Model_recent-genotypes.rds")

print(fit_4, pars = c("LInf_geno", "tZero_geno", "k_geno", "sigma_geno"))

p = c("LInf_geno", "tZero_geno", "k_geno")

samps = as.matrix(fit_4, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)
```

```{r Von Bertalanffy molecular sexing vs visual, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
Sexpike <- fread("Data/Pike/sexed_pike_all_moddeling.csv")

Sexpike2 <- Sexpike%>%
  transmute(Fish_ID, Sex_molecular)

Growthtable <- Pikemaster %>%
  filter(Sample == "Recent")%>%
  transmute(Fish_ID, TL_mm, Length_back, Sample, Age, Cohort, 
            Sex_visual = Sex, 
            Area, Genotype)%>%
  distinct()%>%
  left_join(Sexpike2, by = "Fish_ID")%>%
  drop_na(Sex_visual, Sex_molecular)%>%
  mutate(Area = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek") ~ "Tributary",
                          Area %in% c("NRB", "BAT", "GB", "S", "SB", "U", "KB", "WB", "BEG", "BEZ", "GJB", "VB") ~ "Mesohaline",
                          Area %in% c("P", "KJB", "SAB") ~ "Oligohaline",
                          TRUE ~ Area),
         Sample_bin1 = case_when(Sex_visual == "f" ~ 1,
                                 Sex_visual == "m" ~ 2,
                                 TRUE ~ NA),
         Sample_bin2 = case_when(Sex_molecular == "f" ~ 1,
                                 Sex_molecular == "m" ~ 2,
                                 TRUE ~ NA)) %>%
  drop_na(Sample_bin1, Sample_bin2, Age)%>%
  distinct()

priors <- fread("Data/Pike/Priors_pike.csv")

standata_Pike1 = list(
  Length = Growthtable$Length_back/10,
  Age = Growthtable$Age,
  N = nrow(Growthtable),
  Sample = Growthtable$Sample_bin1,
  linf_mean = mean(priors$Loo), #alt: mean^2/variance & variance/mean
  linf_var = sd(priors$Loo),
  t0_mean = mean(priors$to),
  t0_var = sd(priors$to)^2,
  k_prior = 1,  
  n_groupmax = as.integer(length(Growthtable[Growthtable$Sex_visual == "f",]$Fish_ID)),
  n_group1 = as.integer(length(Growthtable[Growthtable$Sex_visual == "f",]$Fish_ID)),
  n_group2 = as.integer(length(Growthtable[Growthtable$Sex_visual == "m",]$Fish_ID)),
  geno_id = Growthtable$Genotype
)

standata_Pike2 = list(
  Length = Growthtable$Length_back/10,
  Age = Growthtable$Age,
  N = nrow(Growthtable),
  Sample = Growthtable$Sample_bin2,
  linf_mean = mean(priors$Loo), #alt: mean^2/variance & variance/mean
  linf_var = sd(priors$Loo),
  t0_mean = mean(priors$to),
  t0_var = sd(priors$to)^2,
  k_prior = 1,  
  n_groupmax = as.integer(length(Growthtable[Growthtable$Sex_molecular == "f",]$Fish_ID)),
  n_group1 = as.integer(length(Growthtable[Growthtable$Sex_molecular == "f",]$Fish_ID)),
  n_group2 = as.integer(length(Growthtable[Growthtable$Sex_molecular == "m",]$Fish_ID)),
  geno_id = Growthtable$Genotype
)

# Model
stancode <- "Data/Pike/Stan/Simple_VBGF_TZero_sex-specific_gen.stan"

mod = stan_model(stancode, model_name = "pike growth sexing")

#fitting
fit_1 = sampling(mod, iter = 40000, data = standata_Pike1, thin = 100,
                   control = list(adapt_delta = 0.95, max_treedepth = 14))

fit_2 = sampling(mod, iter = 40000, data = standata_Pike2, thin = 100,
                   control = list(adapt_delta = 0.95, max_treedepth = 14))

print(fit_1, pars = c("LInf_f", "LInf_m", "k_f", "k_m", "tZero_f", "tZero_m"))
print(fit_2, pars = c("LInf_f", "LInf_m", "k_f", "k_m", "tZero_f", "tZero_m"))

saveRDS(fit_1, "Data/Pike/Stan/Model_visual-sex-specific.rds")
saveRDS(fit_2, "Data/Pike/Stan/Model_molecular-sex-specific.rds")

p = c("LInf_geno", "tZero_geno", "k_geno")

samps = as.matrix(fit_3, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)

Errorcount <- Growthtable%>%
  mutate(Sexerror = case_when(Sex_molecular != Sex_visual ~ 1,
                              TRUE ~ 0))

length(Errorcount[Errorcount$Sexerror == 1,]$Fish_ID)/length(Errorcount$Fish_ID)
```

```{r Von Bertalanffy curves historic vs recent, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster_sex <- fread("Data/Pike/Pikemaster_sex.csv")
fit_1 <- read_rds("Data/Pike/Stan/Model-recent-vs-historic_complex.rds")

Growthtable1 <- Pikemaster_sex %>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Sample = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek") ~ "Freshwater",
                            TRUE ~ Sample),
         Sample_bin = as.factor(case_when(Sample == "Recent-f" ~ 1,
                                Sample == "Recent-m" ~ 2,
                                Sample == "Historic-f" ~ 3,
                                Sample == "Historic-m" ~ 4,
                                TRUE ~ 5))) %>%
  distinct()

length(unique(Growthtable1[Growthtable1$Sample == "Recent-f",]$Fish_ID))
length(unique(Growthtable1[Growthtable1$Sample == "Recent-m",]$Fish_ID))
length(unique(Growthtable1[Growthtable1$Sample == "Historic-f",]$Fish_ID))
length(unique(Growthtable1[Growthtable1$Sample == "Historic-m",]$Fish_ID))

#Stats
p = c("LInf_area", "tZero_area", "k_area")

samps = as.matrix(fit_1, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)

#extract samples

Incpredict = function(pars, Agei) pars[1] * (1 - exp(-pars[2] * (Agei - (-pars[3]))))

Pikepredict_sex = function(x, quants = c(0.5, 0.05, 0.95), names = c("median", "lower", "upper")) {
	pars = c("LInf_area", "k_area", "tZero_area")
	samps = as.matrix(x, pars = pars)

	# list of 4 phenotypes
	# each element is a matrix, 20000 rows (samples) by 15 age increments
	area_pr = lapply(0:4, \(i) t(apply(samps[, c(1, 6, 11) + i], 1, Incpredict, Agei = 1:15)))

	# convert to a data table summarizing by quantiles
	area_q = lapply(area_pr, \(x) {
		res = data.frame(t(apply(x, 2, quantile, quants)))
		colnames(res) = names
		res$Agei = 1:15
		res
	})
	rbindlist(area_q, idcol = "area_id")
}

samples <- Pikepredict_sex(fit_1)
samples$area_id <- as.factor(samples$area_id)

#plotting

pl_theme =	theme_classic() +
  theme(panel.grid.major = element_line(linewidth = 0.5, colour = "lightgrey"),
        legend.box.background = element_rect(),
        axis.line = element_line(linewidth = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(linewidth = .5, colour = "black"),
        axis.text.x = element_text(size = 10, colour = "black"),
        axis.text.y = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, colour = "black"),
        axis.title.y = element_text(size = 10, colour = "black"),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8, face = "bold"),
        legend.position = c(0.7,0.2),
        plot.title = element_text(size = 12, colour = "black"))

Curve_pop_complex <- ggplot(data = samples[samples$area_id != 5,]) + #exclude freshwater
  geom_ribbon(aes(x = Agei, ymin = lower, ymax = upper, fill = area_id), alpha = 0.5) +
  geom_line(aes(x = Agei, y = median, color = area_id), linewidth = 2) + 
  geom_point(data = Growthtable1, aes(x = Age, y = Length_LI/10, color = Sample_bin), size = 1, alpha = .9) + 
  scale_x_continuous(breaks = seq(1,15,1), labels = c("1","","3","","5","","7","","9","","11","","13","","15"))+
  scale_color_manual(breaks = c(1,2,3,4), values = c("#004643", "#C5D86D", "#00BFB2", "#F1C40F", "#AF3800"), 
                     labels = c("Recent female (n = 400)", "Recent male (n = 362)", "Historic female (n = 338)", "Historic male (n = 197)"))+
  scale_fill_manual(breaks = c(1,2,3,4), values = c("#004643", "#C5D86D", "#00BFB2", "#F1C40F", "#AF3800"), 
                     labels = c("Recent female (n = 400)", "Recent male (n = 362)", "Historic female (n = 338)", "Historic male (n = 197)"))+
  labs(x="Age (years)", y="Total length (cm)", color = "Sample", fill = "Sample", title = "Sex-specific von Bertalanffy growth") + pl_theme

ggsave("Figures/VB-curve_recent-vs-historic-vs-fresh.png", Curve_pop_complex, width = 15, height = 15, units = "cm", dpi = 600, bg = "white")
saveRDS(Curve_pop_complex, "Data/Pike/VB_curve-recent-vs-historic.rds")

```

```{r Von Bertalanffy curves area-specific, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
fit_2 <- read_rds("Data/Pike/Stan/Model-recent-vs-historic_complex_area-specific.rds")

Growthtable2 <- Pikemaster %>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Area = case_when(Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek") ~ "Tributary",
                          Area %in% c("NRB", "BAT", "GB", "S", "SB", "U", "KB", "WB", "BEG", "BEZ", "GJB", "VB") ~ "Mesohaline",
                          Area %in% c("P", "KJB", "SAB") ~ "Oligohaline",
                          TRUE ~ Area),
         Sample_bin = as.factor(case_when(Sample == "Recent" & Area == "Mesohaline" ~ 1,
                                Sample == "Recent" & Area == "Oligohaline" ~ 2,
                                Sample == "Recent" & Area == "Tributary" ~ 3,
                                Sample == "Historic" & Area == "Mesohaline" ~ 4,
                                Sample == "Historic" & Area == "Oligohaline" ~ 5))) %>%
  distinct()

#Stats
p = c("LInf_area", "tZero_area", "k_area")

samps = as.matrix(fit_2, pars = p)
dat = data.frame(
	estimate = apply(samps, 2, median),
	lower = apply(samps, 2, quantile, 0.05),
	upper = apply(samps, 2, quantile, 0.95)
)
tab = cbind(rownames(dat), as.character(signif(dat$estimate, 3)), 
			paste0("(", signif(dat$lower, 3), ", ", signif(dat$upper, 3), ")"))
colnames(tab) = c("Parameter", "Posterior median", "90% CI")

knitr::kable(tab)
	
#extract samples

Pikepredict2 = function(x, quants = c(0.5, 0.05, 0.95), names = c("median", "lower", "upper")) {
	pars = c("LInf_area", "k_area", "tZero_area")
	samps = as.matrix(x, pars = pars)
	
	# list of 4 phenotypes
	# each element is a matrix, 20000 rows (samples) by 15 age increments
	area_pr = lapply(0:4, \(i) t(apply(samps[, c(1, 6, 11) + i], 1, Incpredict, Agei = 1:15)))

	# convert to a data table summarizing by quantiles
	area_q = lapply(area_pr, \(x) {
		res = data.frame(t(apply(x, 2, quantile, quants)))
		colnames(res) = names
		res$Agei = 1:15
		res
	})
	rbindlist(area_q, idcol = "area_id")
}

samples2 <- Pikepredict2(fit_2)
samples2$area_id <- as.factor(samples2$area_id)

#plotting

pl_theme =	theme_classic() +
  theme(panel.grid.major = element_line(),
        legend.box.background = element_rect(),
        axis.line = element_line(linewidth = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(linewidth = .5, colour = "black"),
        axis.text.x = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 14, colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black"),
        axis.title.y = element_text(size = 14, colour = "black"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14, face = "bold"),
        legend.position = c(0.8,0.2),
        plot.title = element_text(size = 14, colour = "black"))

Curve_complex <- ggplot(data = samples2) + 
  geom_ribbon(aes(x = Agei, ymin = lower, ymax = upper, fill = area_id), alpha = 0.5) +
  geom_line(aes(x = Agei, y = median, color = area_id), linewidth = 2) + 
  geom_point(data = Growthtable2, aes(x = Age, y = Length_LI/10, color = Sample_bin), size = 1, alpha = .9) + 
  scale_x_continuous(breaks = seq(1,15,1), labels = c("1","","3","","5","","7","","9","","11","","13","","15"))+
  scale_color_manual(breaks = c(1,2,3,4,5), values = c("#004643", "#C5D86D", "#00BFB2", "#F1C40F", "#AF3800"), 
                     labels = c("Recent mesohaline", "Recent oligohaline", "Tributary", "Historic mesohaline", "historic oligohaline"))+
  scale_fill_manual(breaks = c(1,2,3,4,5), values = c("#004643", "#C5D86D", "#00BFB2", "#F1C40F", "#AF3800"), 
                     labels = c("Recent mesohaline", "Recent oligohaline", "Tributary", "Historic mesohaline", "historic oligohaline"))+
  labs(x="Age (years)", y="Total length (cm)", color = "Sample", fill = "Sample") + pl_theme

ggsave("Figures/VB-curve_recent-vs-historic-vs-fresh_areas.png", Curve_complex,
       width = 15, height = 15, units = "cm", dpi = 600, bg = "white")
```

```{r Von Bertalanffy curves genotype-specific, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
fit_1 <- read_rds("Data/Pike/Stan/Model_historic-genotypes.rds")
fit_2 <- read_rds("Data/Pike/Stan/Model_recent-genotypes.rds")

Growthtable1 <- Pikemaster %>%
  filter(Sample == "Historic") %>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Genotype = as.factor(Genotype)) %>%
  filter(Genotype != 0) %>%
  distinct()

Growthtable2 <- Pikemaster %>%
  filter(Sample == "Recent") %>%
  transmute(Fish_ID, TL_mm, Length_LI, Sample, Age, Cohort, Sex, Area, Genotype)%>%
  mutate(Genotype = as.factor(Genotype)) %>%
  filter(Genotype != 0 & Genotype != 5) %>%
  distinct()

#extract samples

Incpredict = function(pars, Agei) pars[1] * (1 - exp(-pars[2] * (Agei - (-pars[3]))))

Pikepredict = function(x, quants = c(0.5, 0.1, 0.9), names = c("median", "lower", "upper")) {
	pars = c("LInf_geno", "k_geno", "tZero_geno")
	samps = as.matrix(x, pars = pars)

	# list of 4 phenotypes
	# each element is a matrix, 20000 rows (samples) by 15 age increments
	geno_pr = lapply(0:3, \(i) t(apply(samps[, c(1, 5, 9) + i], 1, Incpredict, Agei = 1:15)))

	# convert to a data table summarizing by quantiles
	geno_q = lapply(geno_pr, \(x) {
		res = data.frame(t(apply(x, 2, quantile, quants)))
		colnames(res) = names
		res$Agei = 1:15
		res
	})
	rbindlist(geno_q, idcol = "geno_id")
}

samples <- Pikepredict(fit_1)
samples$geno_id <- as.factor(samples$geno_id)

pl_theme =	theme_classic() +
  theme(panel.grid.major = element_line(linewidth = 0.5, colour = "lightgrey"),
        legend.box.background = element_rect(),
        axis.line = element_line(linewidth = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(linewidth = .5, colour = "black"),
        axis.text.x = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 14, colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black"),
        axis.title.y = element_text(size = 14, colour = "black"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14, face = "bold"),
        legend.position = c(0.8,0.2),
        plot.title = element_text(size = 14, colour = "black"))

#Genotypes: 1 = brackish 1; 2 = brackish 2; 3 = freshwater/anadromous; 5 = freshwater

Historic <- ggplot(data = samples) + 
  geom_ribbon(aes(x = Agei, ymin = lower, ymax = upper, fill = geno_id), alpha = 0.3) +
  geom_line(aes(x = Agei, y = median, color = geno_id), linewidth = 1) + 
  geom_point(data = Growthtable1, aes(x = Age, y = Length_LI/10, color = Genotype), size = 1, alpha = .9) + 
  scale_x_continuous(breaks = seq(1,15,1), labels = c("1","","3","","5","","7","","9","","11","","13","","15"))+
  scale_color_manual(breaks = c(1,2,3,4), values = c("#004643", "#F1C40F", "#00BFB2", "#C5D86D"), 
                     labels = c("Brackish 1", "Brackish 2", "anadromous", "Freshwater"))+
  scale_fill_manual(breaks = c(1,2,3,4), values = c("#004643", "#F1C40F", "#00BFB2", "#C5D86D"), 
                     labels = c("Brackish 1", "Brackish 2", "anadromous", "Freshwater"))+
  labs(x="Age (years)", y="Total length (cm)", color = "Sample", fill = "Sample") + pl_theme

samples2 <- Pikepredict(fit_2)
samples2$geno_id <- as.factor(samples2$geno_id)

Recent <- ggplot(data = samples2) + 
  geom_ribbon(aes(x = Agei, ymin = lower, ymax = upper, fill = geno_id), alpha = 0.3) +
  geom_line(aes(x = Agei, y = median, color = geno_id), linewidth = 1) + 
  geom_point(data = Growthtable2, aes(x = Age, y = Length_LI/10, color = Genotype), size = 1, alpha = .9) + 
  scale_x_continuous(breaks = seq(1,15,1), labels = c("1","","3","","5","","7","","9","","11","","13","","15"))+
  scale_color_manual(breaks = c(1,2,3,4), values = c("#004643", "#F1C40F", "#00BFB2", "#C5D86D"), 
                     labels = c("Brackish 1", "Brackish 2", "anadromous", "Freshwater"))+
  scale_fill_manual(breaks = c(1,2,3,4), values = c("#004643", "#F1C40F", "#00BFB2", "#C5D86D"), 
                     labels = c("Brackish 1", "Brackish 2", "anadromous", "Freshwater"))+
  labs(x="Age (years)", y="Total length (cm)", color = "Sample", fill = "Sample") + pl_theme

Recent_vs_historic <- ggarrange(Recent, Historic)

ggsave("Figures/VB-curve_recent-vs-historic-genotypes.png", Recent_vs_historic, width = 30, height = 15, units = "cm", dpi = 600, bg = "white")
```

## Age-specific growth

```{r Clean up LUNG data for modelling, include=FALSE, eval=FALSE}
Data <- fread("Data/Environment/LUNG_data_Bodden_1970-2023.csv")

Data$Value <- as.numeric(sub(",", ".", Data$Value))

names(Data) <- c("ID", "Name", "Waterbody", "Date", "Year", "Day", "Month", "Parameter_short", "Parameter", "Sign", "Value", "Unit", "Depth",
                 "HW_Geo", "RW_Geo", "Visibility")

Data1 <- Data %>%
  filter(Parameter_short %in% c("CHLOROPHL", "N", "P", "SAL", "W-T"))%>%
  mutate(Date = as.Date(lubridate::parse_date_time(gsub("\ .", "-", Date), orders = "dmy")))%>%
  group_by(ID, Name, Date, Parameter_short)%>%
  dplyr::mutate(Value = mean(Value, na.rm = TRUE))%>%
  distinct()%>%
  pivot_wider(names_from = "Parameter_short", values_from = "Value")
  
Data_summary <- Data1 %>%
  mutate(Area = case_when(Waterbody %in% c("Kubitzer Bodden", "Schaproder Bodden", "Vitter Bodden") ~ "WRB",
                          Waterbody %in% c("Gr. Jasmunder Bodden", "Breetzer Bodden", "Rassower Strom") ~ "NRB",
                          Waterbody %in% c("Daenische Wiek", "Greifswalder Bodden") ~ "GB",
                          Waterbody %in% c("Peenestrom", "Achterwasser") ~ "P",
                          Waterbody %in% c("Barther Fahrwasser", "Grabow", "Barther Bodden") ~ "BAT",
                          Waterbody == "Andershofer Bucht" ~ "S",
                          Waterbody == "Kl. Jasmunder Bodden" ~ "KJB",
                          Waterbody == "Saaler Bodden" ~ "SAB"))%>%
  group_by(Area, Year, Month)%>%
  dplyr::mutate(SAL_SD = sd(SAL, na.rm = TRUE))%>%
  dplyr::reframe(Area, Year, Month,
                 Secchi_m = mean(Visibility, na.rm = TRUE),
                 Chla_mg_m3 = mean(CHLOROPHL, na.rm = TRUE),
                 Total_N = mean(N, na.rm = TRUE),
                 Total_P = mean(P, na.rm = TRUE),
                 SAL_PSU = mean(SAL, na.rm = TRUE),
                 SAL_SD = mean(SAL_SD, na.rm = TRUE),
                 WT_Celsius = mean(`W-T`, na.rm = TRUE))%>%
  ungroup()%>%
  distinct()

Data_complete <- Data_summary %>%
  group_by(Area, Year)%>%
  dplyr::mutate(Months_highSAL = sum(SAL_PSU > 10, na.rm = TRUE))%>%
  ungroup()
  
fwrite(Data_complete, "Data/Environment/Lungdata-monthly-means.csv")
```

```{r import and process surface air temperature, include=FALSE, eval=FALSE}
rm(list = ls())

# Load the NetCDF file
era5 <- rast("Data/Environment/ERA5_merged_1970_2024.nc")

# Explore the structure
print(era5)

slice <- era5[[1]]

# Basic plot with color palette and labels
plot(slice,
     main = "ERA5 2m Temperature (First Time Slice)",
     col = terrain.colors(50),
     xlab = "Longitude", ylab = "Latitude")

map("world", add = TRUE, col = "black")

# Get the names
layer_names <- names(era5)

# Extract numeric part after "="
seconds_since_epoch <- as.numeric(gsub(".*=", "", layer_names))

# Convert to date-time (origin is 1970-01-01)
layer_times <- as.POSIXct(seconds_since_epoch, origin = "1970-01-01", tz = "UTC")

time(era5) <- layer_times

head(time(era5))

era5_celsius <- era5 - 273.15

plot(era5_celsius[[201]])

tbase <- 10
tupper <- 24

gdd_daily <- clamp(era5_celsius - tbase, lower = 0, upper = tupper - tbase)

# Extract year from each date
years <- format(time(gdd_daily), "%Y")

# Group by year and sum GDDs
gdd_yearly <- tapp(gdd_daily, years, fun = sum)

# 1. Extract layer names and get years
years <- names(gdd_yearly)
years <- sub("X", "", years)

# 2. Calculate mean GDD per year (ignores NAs)
mean_gdd <- global(gdd_yearly, fun = "mean", na.rm = TRUE)

# 3. Combine into data frame
gdd_df <- data.frame(
  Year = as.integer(years),
  GDD = mean_gdd[, 1]
)

fwrite(gdd_df, "Data/Environment/GDD_Bodden.csv")
```

```{r calculate size-independent growth index, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
Sexpike <- fread("Data/Pike/molsexed_pike_historic.csv")

Sexpike2 <- Sexpike %>%
  transmute(Oldenburg_ID = Fish_ID, 
            Sex_molecular = Sex_Updated) %>%
  distinct()

Pikemaster$Oldenburg_ID <- gsub("\\.", "-", Pikemaster$Oldenburg_ID)

#check length of historic pike before join
length(unique(Pikemaster[Pikemaster$Sample == "Historic",]$Fish_ID))

Pikemaster2 <- Pikemaster %>%
  left_join(Sexpike2, by = "Oldenburg_ID")

unique(Pikemaster2$Sex)

Pikemaster3 <- PikeSexPikemaster3 <- Pikemaster2 %>%
  mutate(Sex = case_when(Sex == ""|is.na(Sex) ~ Sex_molecular,
                         Sex == "" ~ "u",
                         TRUE ~ Sex)) %>%
  mutate(Sex = case_when(is.na(Sex) ~ "u",
                         TRUE ~ Sex))

#check sample size again
length(unique(Pikemaster3$Fish_ID))
length(unique(Pikemaster3[Pikemaster3$Sample == "Historic",]$Fish_ID))

#check sex variable
unique(Pikemaster3$Sex)

fwrite(Pikemaster3, "Data/Pike/Pikemaster_sexed.csv")

#linear regression of length at age i + 1 with length at age i
Pikemaster4 <- Pikemaster3 %>%
  filter(Sex %in% c("f", "m", "u")) %>%
  arrange(Fish_ID, Lifeyear) %>%
  group_by(Fish_ID) %>%
  dplyr::mutate(Length_back2 = lag(Length_back)) %>%
  ungroup()

#Model Length at age with length at age-1
#regression for females
LM_f <- lm(Length_back ~ Length_back2, data = Pikemaster4[Pikemaster4$Sex == "f",])
#regression for males
LM_m <- lm(Length_back ~ Length_back2, data = Pikemaster4[Pikemaster4$Sex == "m",])
#regression for unknown sex
LM_u <- lm(Length_back ~ Length_back2, data = Pikemaster4[Pikemaster4$Sex == "u",])

#Look at fit
summary(LM_f)
summary(LM_m)
summary(LM_u)

#quick visual sanity check
ggplot(Pikemaster4[Pikemaster4$Sex == "f"|Pikemaster4$Sex == "m",], aes(Length_back2, Length_back, color = Sex))+
  geom_point()+
  geom_smooth(method = "lm")

#Extract slopes
slope_f <- coef(LM_f)[2]
slope_m <- coef(LM_m)[2]
slope_u <- coef(LM_u)[2]

#Correct year-specific back-calculated length for size
Growthdata <- Pikemaster4 %>%
  mutate(GIndex = case_when(Sex == "f" ~ Length_back - slope_f * Length_back2,
                            Sex == "m" ~ Length_back - slope_m * Length_back2,
                            Sex == "u" ~ Length_back - slope_u * Length_back2)) %>%
  mutate(GIndex = case_when(is.na(GIndex) == "TRUE" ~ Length_back,
                            TRUE ~ GIndex)) %>%
  transmute(Fish_ID, Sample, 
            Lifeyear = as.factor(Lifeyear), 
            Cohort, Year, Sex, Area, Pisc_mm, 
            Genotype = as.factor(Genotype), 
            GIndex) %>%
  drop_na() %>%
  distinct()

length(unique(Growthdata$Fish_ID))
length(unique(Growthdata[Growthdata$Sample == "Historic",]$Fish_ID))

fwrite(Growthdata, "Data/Pike/Pikedata_agespecmodel.csv")
```

```{r merge data for mixed modelling, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")
LUNGdata <- fread("Data/Environment/Lungdata-monthly-means.csv")
GDDdata <- fread("Data/Environment/GDD_Bodden.csv")

#Make yearly means LUNGdata
LUNGdata_years <- LUNGdata %>%
  group_by(Year, Area)%>%
  reframe(Secchi_m = mean(Secchi_m, na.rm = TRUE),
          Chla_mg_m3 = mean(Chla_mg_m3, na.rm = TRUE),
          Total_N = mean(Total_N, na.rm = TRUE),
          Total_P = mean(Total_P, na.rm = TRUE),
          SAL_PSU = mean(SAL_PSU, na.rm = TRUE),
          SAL_SD = mean(SAL_SD, na.rm = TRUE),
          Months_highSAL = mean(Months_highSAL, na.rm = TRUE),
          WT_Celsius = mean(WT_Celsius, na.rm = TRUE))%>%
  ungroup()%>%
  distinct()

#Join with LUNGdata
Growthdata2 <- Growthdata%>%
  left_join(LUNGdata_years, by = c("Area", "Year"))%>%
  left_join(GDDdata, by = "Year")

length(unique(Growthdata2$Fish_ID))
length(unique(Growthdata2[Growthdata2$Sample == "Historic",]$Fish_ID))

Growthdata3 <- Growthdata2 %>%
  transmute(Fish_ID,
            Sample = as.factor(Sample),
            Lifeyear,
            Cohort = as.factor(Cohort),
            Year,
            Sex = as.factor(Sex),
            Area = as.factor(case_when(Area %in% c("KB", "SB", "BEZ", "BAT", "S", "GB", "WB", "BEG", "GJB", "NRB", "U", "VB") ~ "Mesohaline",
                                       Area %in% c("P", "SAB", "DZB", "KJB") ~ "Oligohaline",
                                       TRUE ~ "Freshwater")),
            Pisc_mm,
            Genotype = as.factor(Genotype),
            GIndex, Secchi_m, Chla_mg_m3, Total_N, Total_P, SAL_PSU, SAL_SD, Months_highSAL, WT_Celsius, GDD)%>%
  filter(GIndex > 0)

fwrite(Growthdata3, "Data/Pike/Pikedata_agespecmodel.csv")
```


```{r plot environmental variables for appenmdix, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata3 <- fread("Data/Pike/Pikedata_agespecmodel.csv")
LUNGdata <- fread("Data/Environment/Lungdata-monthly-means.csv")
GDDdata <- fread("Data/Environment/GDD_Bodden.csv")

area_zone_lookup <- function(area) {
  dplyr::case_when(area %in% c("KB","SB","BEZ","BAT","S","GB","WB","WRB","BEG","GJB","NRB","U","VB") ~ "Mesohaline",
                    area %in% c("P","SAB","DZB","KJB") ~ "Oligohaline",
                    TRUE ~ "Freshwater")
}

LUNGdata_years <- LUNGdata %>%
  dplyr::filter(!is.na(Area)) %>%
  dplyr::mutate(Zone = area_zone_lookup(Area)) %>%
  dplyr::group_by(Year, Zone) %>%
  dplyr::reframe(Secchi_m = mean(Secchi_m, na.rm = TRUE),
                 Chla_mg_m3 = mean(Chla_mg_m3, na.rm = TRUE),
                 Total_N = mean(Total_N, na.rm = TRUE),
                 Total_P = mean(Total_P, na.rm = TRUE),
                 SAL_PSU = mean(SAL_PSU, na.rm = TRUE),
                 SAL_SD = mean(SAL_SD, na.rm = TRUE),
                 WT_Celsius = mean(WT_Celsius, na.rm = TRUE)) %>%
  dplyr::ungroup() %>%
  dplyr::distinct()

env_continuous_vars <- c("Secchi_m","Chla_mg_m3","Total_N","Total_P","SAL_PSU","SAL_SD","WT_Celsius")

env_long <- LUNGdata_years %>%
  tidyr::pivot_longer(cols = dplyr::all_of(env_continuous_vars), names_to = "Variable", values_to = "value") %>%
  dplyr::transmute(Year, Area = Zone, Variable, value)

gdd_long <- GDDdata %>%
  dplyr::transmute(Year, Area = NA_character_, Variable = "GDD", value = GDD)

# --- GIndex: yearly boxplots (full per-fish distribution per year), from Growthdata3 ---
gindex_long <- Growthdata3 %>%
  dplyr::transmute(Year = as.numeric(Year), Area = as.character(Area), Variable = "GIndex", value = GIndex)

Env_multi <- dplyr::bind_rows(env_long, gdd_long) %>%
  dplyr::mutate(Variable = factor(Variable,
                                   levels = c("GIndex","Secchi_m","Chla_mg_m3","Total_N","Total_P",
                                              "SAL_PSU","SAL_SD","WT_Celsius","GDD"))) %>%
  filter(Area != "Freshwater")

var_labels <- c(
  "GIndex"     = "Growth index",
  "Secchi_m"   = "Secchi depth (m)",
  "Chla_mg_m3" = "Chl a (mg/m³)",
  "Total_N"    = "Total N",
  "Total_P"    = "Total P",
  "SAL_PSU"    = "Salinity (PSU)",
  "SAL_SD"     = "Salinity SD",
  "WT_Celsius" = "Water temp (°C)",
  "GDD"        = "Growing degree days"
)

area_colors <- c("Mesohaline" = "#0072B2", "Oligohaline" = "#E69F00", "Freshwater" = "#009E73")

EnvMultiplot <- ggplot(Env_multi, aes(x = Year, y = value)) +
  geom_boxplot(data = dplyr::filter(Env_multi, Variable == "GIndex"),
               aes(x = Year, y = value, group = interaction(Year, Area), colour = Area),
               position = position_dodge2(preserve = "single", padding = 0.2),
               outlier.size = 0.5, linewidth = 0.4) +
  geom_line(data = dplyr::filter(Env_multi, Variable %in% env_continuous_vars),
            aes(colour = Area), linewidth = 0.6) +
  geom_smooth(data = dplyr::filter(Env_multi, Variable %in% env_continuous_vars),
              aes(colour = Area), method = "loess", se = TRUE, linewidth = 0.7) +
  geom_line(data = dplyr::filter(Env_multi, Variable == "GDD"),
            colour = "grey30", linewidth = 0.7) +
  geom_vline(xintercept = 1989, linetype = "dashed", colour = "red", linewidth = 0.6) +
  coord_cartesian(xlim = c(1976, 2022)) +
  facet_wrap(~ Variable, scales = "free_y", ncol = 3, labeller = labeller(Variable = var_labels)) +
  scale_colour_manual(values = area_colors, na.translate = FALSE) +
  theme_classic() +
  labs(x = "Year", y = NULL, colour = "Area") +
  theme(legend.position = "bottom",
        panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.5),
        strip.text = element_text(size = 10, colour = "black"),
        plot.title = element_text(size = 10, colour = "black"),
        axis.text = element_text(size = 9, colour = "black"),
        axis.title = element_text(size = 10, colour = "black"),
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 9))

ggsave("Figures/Environment_Multiplot.png", EnvMultiplot, width = 20, height = 20, units = "cm", dpi = 600, bg = "white")
```

```{r data exploration, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

#Any bad years?
ggplot(Growthdata, aes(x = factor(Year), y = GIndex, colour = Sample))+
  geom_boxplot(lwd = .5, outlier.shape = NA, width = .6, position = position_dodge(width = NULL))+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90))

#Any bad cohorts?
ggplot(Growthdata, aes(x = factor(Cohort), y = GIndex, colour = Sample))+
  geom_boxplot(lwd = .5, outlier.shape = NA, width = .6, position = position_dodge(width = NULL))+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90))

par(mfrow = c(3, 3))
dotchart(Growthdata$GIndex, color = as.factor(Growthdata$Sample), main = "Color = Sample")
dotchart(Growthdata$GIndex, color = as.factor(Growthdata$Cohort), main = "Color = Cohort")
dotchart(Growthdata$GIndex, color = as.factor(Growthdata$Year), main = "Color = Year")
dotchart(Growthdata$GIndex, color = as.factor(Growthdata$Sex), main = "Color = Sex")
dotchart(Growthdata$GIndex, color = as.factor(Growthdata$Area), main = "Color = Sample")
dotchart(Growthdata$GIndex, color = as.factor(Growthdata$Genotype), main = "Color = Sample")

par(mfrow = c(2, 2))
boxplot(Growthdata$GIndex~Growthdata$Lifeyear, ylab = "Growth increment", xlab = "Age")
boxplot(Growthdata$GIndex~Growthdata$Sample, ylab = "Growth increment", xlab = "Sample")
boxplot(Growthdata$GIndex~Growthdata$Cohort, ylab = "Growth increment", xlab = "Cohort")
boxplot(Growthdata$GIndex~Growthdata$Year, ylab = "Growth increment", xlab = "Year")

par(mfrow = c(2, 2))
boxplot(Growthdata$GIndex~Growthdata$Sex, ylab = "Growth increment", xlab = "Sex")
boxplot(Growthdata$GIndex~Growthdata$Area, ylab = "Growth increment", xlab = "Area")
boxplot(Growthdata$GIndex~Growthdata$Genotype, ylab = "Growth increment", xlab = "Genotype")
plot(Growthdata$GIndex~Growthdata$Pisc_mm, ylab = "Growth increment", xlab = "Piscring")

hist(Growthdata$GIndex, main = "", xlab = "Growth index")
hist(Growthdata$Pisc_mm, main = "", xlab = "Piscivory increment")
```

```{r model random effects, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

fit_base1 <- brm(GIndex ~ Lifeyear + Sex + Sample + Genotype + Area + (1|Fish_ID),
                 data = Growthdata, family = Gamma(link = "log"),
                 control = list(max_treedepth = 15, adapt_delta = 0.95),
                 iter = 10000, warmup = 5000, chains = 4)

saveRDS(fit_base1, "Data/GLMM_output/Basemodel_randomID.rds")

loo_base1 <- loo(fit_base1)
saveRDS(loo_base1, "Data/GLMM_output/LOO_basemodel_randomID.rds")

fit_base2 <- brm(GIndex ~ Lifeyear + Sex + Sample + Genotype + Area + (1|Fish_ID) + (1|Year),
                 data = Growthdata, family = Gamma(link = "log"),
                 control = list(max_treedepth = 15, adapt_delta = 0.95),
                 iter = 10000, warmup = 5000, chains = 4)

saveRDS(fit_base2, "Data/GLMM_output/Basemodel_randID-randyear.rds")

loo_base2 <- loo(fit_base2)
saveRDS(loo_base2, "Data/GLMM_output/LOO_basemodel_randID-randyear.rds")

fit_base3 <- brm(GIndex ~ Lifeyear + Sex + Sample + Genotype + Area + (1|Fish_ID) + (1|Year) + (1|Cohort),
                 data = Growthdata, family = Gamma(link = "log"),
                 control = list(max_treedepth = 15, adapt_delta = 0.95),
                 iter = 10000, warmup = 5000, chains = 4)

saveRDS(fit_base3, "Data/GLMM_output/Basemodel_randID-randyear-randcorhort.rds")


loo_base3 <- loo(fit_base3)
saveRDS(loo_base3, "Data/GLMM_output/LOO_basemodel_randID-randyear-randcorhort.rds")
```

```{r evaluate random effects, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

fit_base1 <- read_rds("Data/GLMM_output/Basemodel_randomID.rds")
fit_base2 <- read_rds("Data/GLMM_output/Basemodel_randID-randyear.rds")
fit_base3 <- read_rds("Data/GLMM_output/Basemodel_randID-randyear-randcorhort.rds")

loo_base1 <- read_rds("Data/GLMM_output/LOO_basemodel_randomID.rds")
loo_base2 <- read_rds("Data/GLMM_output/LOO_basemodel_randID-randyear.rds")
loo_base3 <- read_rds("Data/GLMM_output/LOO_basemodel_randID-randyear-randcorhort.rds")

loo_compare(loo_base1, loo_base2, loo_base3)

#FishID, Year, and Cohort are significant random effects
```

```{r model interaction effects, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

#check sample size

length(unique(Growthdata[Growthdata$Sample == "Historic",]$Fish_ID))

#Model interactions
#No interaction

fit_fixedAll <- brm(GIndex ~ Lifeyear + Sex + Sample + Genotype + Area + (1|Fish_ID) + (1|Year) + (1|Cohort),
                    data = Growthdata, family = Gamma(link = "log"),
                    control = list(max_treedepth = 15, adapt_delta = 0.95),
                    iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_fixedAll, "Data/GLMM_output/Model_fixed-nointeraction.rds")

loo_int0 <- loo(fit_fixedAll, cores = 1)
saveRDS(loo_int0, "Data/GLMM_output/Loo-nointeraction.rds")

#Threeway interaction age x sample x genotype

fit_HistYearGenointeract <- brm(GIndex ~ Lifeyear + Sex + Lifeyear * Sample * Genotype + Area + (1|Fish_ID) + (1|Year) + (1|Cohort),
                        data = Growthdata, family = Gamma(link = "log"),
                        control = list(max_treedepth = 15, adapt_delta = 0.95),
                        iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_HistYearGenointeract, "Data/GLMM_output/Model_fixed-hist_year-geno-interaction.rds")

loo_int1 <- loo(fit_HistYearGenointeract, cores = 1)
saveRDS(loo_int1, "Data/GLMM_output/Loo-HistYearGenointeraction.rds")

#Just age x sample

fit_HistYearinteract <- brm(GIndex ~ Lifeyear + Sex + Lifeyear * Sample + Genotype + Area + (1|Fish_ID) + (1|Year) + (1|Cohort),
                        data = Growthdata, family = Gamma(link = "log"),
                        control = list(max_treedepth = 15, adapt_delta = 0.95),
                        iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_HistYearinteract, "Data/GLMM_output/Model_fixed-Hist-interaction.rds")

loo_int2 <- loo(fit_HistYearinteract, cores = 1)
saveRDS(loo_int2, "Data/GLMM_output/Loo-HistYearinteraction.rds")

#just sample x genotype

fit_HistGenointeract <- brm(GIndex ~ Lifeyear + Sex + Sample * Genotype + Lifeyear + Area + (1|Fish_ID) + (1|Year) + (1|Cohort),
                                data = Growthdata, family = Gamma(link = "log"),
                                control = list(max_treedepth = 15, adapt_delta = 0.95),
                                iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_HistGenointeract, "Data/GLMM_output/Model_fixed-Samp-Geno-interaction.rds")

loo_int3 <- loo(fit_HistGenointeract, cores = 1)
saveRDS(loo_int3, "Data/GLMM_output/Loo-HistGenointeraction.rds")
```

```{r evaluate interaction effects, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

fit_fixedAll <- read_rds("Data/GLMM_output/Model_fixed-nointeraction.rds")
fit_HistYearGenointeract <- read_rds("Data/GLMM_output/Model_fixed-hist_year-geno-interaction.rds")
fit_HistYearinteract <- read_rds("Data/GLMM_output/Model_fixed-Hist-interaction.rds")
fit_HistGenointeract <- read_rds("Data/GLMM_output/Model_fixed-Samp-Geno-interaction.rds")

loo_int0 <- read_rds("Data/GLMM_output/Loo-nointeraction.rds")
loo_int1 <- read_rds("Data/GLMM_output/Loo-HistYearGenointeraction.rds")
loo_int2 <- read_rds("Data/GLMM_output/Loo-HistYearinteraction.rds")
loo_int3 <- read_rds("Data/GLMM_output/Loo-HistGenointeraction.rds")

summary(fit_HistYearGenointeract)

loo_compare(loo_int0, loo_int1, loo_int2, loo_int3)

#Threeway interaction sample x genotype x age is the most significant interaction!
```

```{r modelling fixed effects, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

#Test environmental variables
# Decide on trophic measure
cor(Growthdata[, c("Chla_mg_m3", "Total_N", "Total_P", "Secchi_m")], use = "pairwise.complete.obs")
complete_idx <- complete.cases(Growthdata[, c("Chla_mg_m3", "Total_N", "Total_P", "Secchi_m")])

fa_result <- factanal(
  Growthdata[complete_idx, c("Chla_mg_m3", "Total_N", "Total_P", "Secchi_m")],
  factors = 1,
  rotation = "varimax",
  scores = "regression")

#Make mean of z-scores for Chla, P and N
Growthdata$ProductivityIndex <- rowMeans(Growthdata[, c("Chla_mg_m3", "Total_N", "Total_P")] * c(1, 1, 1), na.rm = TRUE)

ggplot(Growthdata, aes(Year, ProductivityIndex, color = Area))+
  geom_point()

Growthdata1 <- Growthdata %>%
  drop_na(Lifeyear, Sample, Sex, Genotype, Area, Pisc_mm, GDD)%>%
  filter(GIndex > 0)

Growthdata2 <- Growthdata1 %>%
  drop_na(ProductivityIndex, SAL_PSU)

#Model fixed effects (all obs.) across the population

fit_alleffects <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex + Area +
                        Pisc_mm + GDD +
                        (1|Fish_ID) + (1|Cohort) + (1|Year),
                      data = Growthdata1, family = Gamma(link = "log"),
                      control = list(max_treedepth = 15, adapt_delta = 0.95),
                      iter = 500, warmup = 250, chains = 4)

saveRDS(fit_alleffects, "Data/GLMM_output/Model_all-effects.rds")

loo_fitall1 <- loo(fit_alleffects)
saveRDS(loo_fitall1, "Data/GLMM_output/LOO_Model_all-effects.rds")

fit_noGDD <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex + Area +
                   Pisc_mm +
                   (1|Fish_ID) + (1|Year) + (1|Cohort),
                 data = Growthdata1, family = Gamma(link = "log"),
                 control = list(max_treedepth = 15, adapt_delta = 0.95),
                 iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_noGDD, "Data/GLMM_output/Model_no-GDD.rds")

loo_noGDD <- loo(fit_noGDD)
saveRDS(loo_noGDD, "Data/GLMM_output/LOO_Model_no-GDD.rds")

fit_noPisc <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex + Area +
                    GDD +
                    (1|Fish_ID) + (1|Year) + (1|Cohort),
                  data = Growthdata1, family = Gamma(link = "log"),
                  control = list(max_treedepth = 15, adapt_delta = 0.95),
                  iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_noPisc, "Data/GLMM_output/Model_no-Pisc.rds")

loo_noPisc <- loo(fit_noPisc)
saveRDS(loo_noPisc, "Data/GLMM_output/LOO_Model_no-Pisc.rds")

fit_noArea <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex +
                    Pisc_mm + GDD +
                    (1|Fish_ID) + (1|Year) + (1|Cohort),
                  data = Growthdata1, family = Gamma(link = "log"),
                  control = list(max_treedepth = 15, adapt_delta = 0.95),
                  iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_noArea, "Data/GLMM_output/Model_no-Area.rds")

loo_noArea <- loo(fit_noArea)
saveRDS(loo_noArea, "Data/GLMM_output/LOO_Model_no-Area.rds")

fit_noSex <- brm(GIndex ~ Lifeyear * Sample * Genotype + Area +
                   Pisc_mm + GDD +
                   (1|Fish_ID) + (1|Year) + (1|Cohort),
                 data = Growthdata1, family = Gamma(link = "log"),
                 control = list(max_treedepth = 15, adapt_delta = 0.95),
                 iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_noSex, "Data/GLMM_output/Model_no-Sex.rds")

loo_noSex <- loo(fit_noSex)
saveRDS(loo_noSex, "Data/GLMM_output/LOO_Model_no-Sex.rds")

# Model growth with all fixed effects and productivity factor (limited sample)

fit_allefects2 <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex + Area +
                        Pisc_mm + GDD + ProductivityIndex + SAL_PSU +
                        (1|Fish_ID) + (1|Year) + (1|Cohort),
                      data = Growthdata2, family = Gamma(link = "log"),
                      control = list(max_treedepth = 15, adapt_delta = 0.95),
                      iter = 10000, warmup = 5000, chains = 4)

saveRDS(fit_allefects2, "Data/GLMM_output/Model_all-effects2.rds")

loo_alleffects2 <- loo(fit_allefects2)
saveRDS(loo_alleffects2, "Data/GLMM_output/LOO_Model_all-effects2.rds")

fit_noSal <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex + Area +
                     Pisc_mm + GDD + ProductivityIndex +
                     (1|Fish_ID) + (1|Year) + (1|Cohort),
                   data = Growthdata2, family = Gamma(link = "log"),
                   control = list(max_treedepth = 15, adapt_delta = 0.95),
                   iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_noSal, "Data/GLMM_output/Model_all-effects2-nosal.rds")

loo_noSal <- loo(fit_noSal)
saveRDS(loo_noSal, "Data/GLMM_output/LOO_Model_all-effects2-nosal.rds")

fit_noProd <- brm(GIndex ~ Lifeyear * Sample * Genotype + Sex + Area +
                   Pisc_mm + GDD + SAL_PSU +
                   (1|Fish_ID) + (1|Year) + (1|Cohort),
                 data = Growthdata2, family = Gamma(link = "log"),
                 control = list(max_treedepth = 15, adapt_delta = 0.95),
                 iter = 40000, warmup = 20000, chains = 4)

saveRDS(fit_no_Prod, "Data/GLMM_output/Model_all-effects2-nosal.rds")

loo_noProd <- loo(fit_noProd)
saveRDS(loo_noProd, "Data/GLMM_output/LOO_Model_all-effects2-nosal.rds")
```

```{r evaluate fixed effects, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv")

#Models with all obs
fit_alleffects <- read_rds("Data/GLMM_output/Model_all-effects.rds")
fit_noGDD <- read_rds("Data/GLMM_output/Model_no-GDD.rds")
fit_noPisc <- read_rds("Data/GLMM_output/Model_no-Pisc.rds")
fit_noArea <- read_rds("Data/GLMM_output/Model_no-Area.rds")
fit_noSex <- read_rds("Data/GLMM_output/Model_no-Sex.rds")

#Loo with all obs
loo_fitall1 <- read_rds("Data/GLMM_output/LOO_Model_all-effects.rds")
loo_noGDD <- read_rds("Data/GLMM_output/LOO_Model_no-GDD.rds")
loo_noPisc <- read_rds("Data/GLMM_output/LOO_Model_no-Pisc.rds")
loo_noArea <- read_rds("Data/GLMM_output/LOO_Model_no-Area.rds")
loo_noSex <- read_rds("Data/GLMM_output/LOO_Model_no-Sex.rds")

loo_compare(loo_fitall1, loo_noGDD, loo_noPisc, loo_noArea, loo_noSex)

#Models for Prod and Sal effects
fit_allefects2 <- read_rds("Data/GLMM_output/Model_all-effects2.rds")
fit_noSal <- read_rds("Data/GLMM_output/Model_all-effects2-nosal.rds")
fit_no_Prod <- read_rds("Data/GLMM_output/Model_all-effects2-nosal.rds")

loo_alleffects2 <- read_rds("Data/GLMM_output/LOO_Model_all-effects2.rds")
loo_noSal <- read_rds("Data/GLMM_output/LOO_Model_all-effects2-nosal.rds")
loo_noProd <- read_rds("Data/GLMM_output/LOO_Model_all-effects2-nosal.rds")

loo_compare(loo_alleffects2, loo_noSal, loo_noProd)

# significant effects?
```

```{r modelling age-specific growth figures, include=FALSE, eval=FALSE}
rm(list = ls())

Growthdata <- fread("Data/Pike/Pikedata_agespecmodel.csv") 
Growthmodel <- read_rds("Data/GLMM_output/Model_fixed-hist_year-geno-interaction.rds")

Growthdata <- Growthdata %>% 
  filter(GIndex > 0) %>% 
  reframe(Fish_ID, GIndex, Year, Cohort, Sample, 
          Lifeyear = as.factor(Lifeyear), 
          Sex = as.factor(Sex), 
          Area = Area,
          Genotype = Genotype, 
          Months_highSAL, Pisc_mm = Pisc_mm, 
          Secchi_m = scale(Secchi_m), 
          Chla_mg_m3 = scale(Chla_mg_m3), 
          Total_N = scale(Total_N),
          Total_P = scale(Total_P), 
          SAL_PSU = scale(SAL_PSU), 
          SAL_SD = scale(SAL_SD), 
          WT_Celsius = scale(WT_Celsius), 
          GDD = scale(GDD)) %>%
  filter(!Area %in% c("Peene", "Barthe", "Sehrowbach", "Duwenbeek", "Beek")) %>%
  distinct()

newdata <- expand.grid(Lifeyear = 1:13,
                       Sample = c("Historic", "Recent"),
                       Genotype = c(1:4),
                       Sex = c("f", "m"),
                       Area = unique(Growthdata$Area))

pred <- fitted(Growthmodel,
               newdata = newdata,
               re_formula = NA,
               summary = TRUE)

plot_data <- cbind(newdata, pred)

plot_data2 <- plot_data %>%
  mutate(Lifeyear_num = as.numeric(as.character(Lifeyear))) %>%
  semi_join(
    Growthdata %>%
      mutate(Lifeyear_num = as.numeric(as.character(Lifeyear))) %>%
      distinct(Genotype, Sample, Lifeyear_num),
    by = c("Genotype", "Sample", "Lifeyear_num")
  )

#Age-specific effects
plot_theme <- theme(panel.grid.major = element_line(linewidth = .3, colour = "lightgrey"),
        legend.position = c(0.7,0.8),
        legend.background = element_blank(),
        legend.box.background = element_rect(),
        axis.line = element_line(linewidth = 1, colour = "black", linetype = 1),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        plot.title = element_text(size = 12, colour = "black"),
        axis.title = element_blank(),
        legend.text = element_text(size = 10, colour = "black"),
        legend.title = element_text(size = 10, colour = "black"),
        legend.key.size = unit(1,"line"))

Geno1 <- ggplot(Growthdata[Growthdata$Genotype == 1,], aes(as.factor(Lifeyear), GIndex, fill = Sample))+
  geom_boxplot(lwd = .5, outlier.shape = NA, width = .6, position = position_dodge(width = NULL))+
  # stat_summary(fun.data = function(x) data.frame(ymin = quantile(x, 0.025), y = median(x), ymax = quantile(x, 0.975)),
  # geom = "pointrange",  position = position_dodge(width = 0.75)) +
  #geom_smooth(method = "lm")+
  labs(title = "Genotype 1 (brackish)", x="Age (years)", y=expression("Growth index"), fill="Sample")+
  scale_x_discrete(limits = c(1:10),
                  breaks=c(1:10))+
  scale_y_continuous(limits = c(100, 500)) +
  scale_fill_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 190)", "Recent (N = 269)"))+
  theme_classic()+
  plot_theme


Geno2 <- ggplot(Growthdata[Growthdata$Genotype == 2,], aes(as.factor(Lifeyear), GIndex, fill = Sample))+
  geom_boxplot(lwd = .5, outlier.shape = NA, width = .6, position = position_dodge(width = NULL))+
  #stat_summary(fun.data = function(x) data.frame(ymin = quantile(x, 0.025), y = median(x), ymax = quantile(x, 0.975)),
  #geom = "pointrange",  position = position_dodge(width = 0.75)) +
  #geom_smooth(method = "lm")+
  labs(title = "Genotype 2 (brackish)", x="Age (years)", y=expression("Growth index"), fill="Sample")+
  scale_x_discrete(limits = c(1:10),
                  breaks=c(1:10))+
  scale_y_continuous(limits = c(100, 500)) +
  scale_fill_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 111)", "Recent (N = 87)"))+
  theme_classic()+
  plot_theme

Geno3 <- ggplot(Growthdata[Growthdata$Genotype == 3,], aes(as.factor(Lifeyear), as.numeric(GIndex), fill = Sample))+
  geom_boxplot(lwd = .5, outlier.shape = NA, width = .6, position = position_dodge(width = NULL))+
  #stat_summary(fun.data = function(x) data.frame(ymin = quantile(x, 0.025), y = median(x), ymax = quantile(x, 0.975)),
  #geom = "pointrange",  position = position_dodge(width = 0.75)) +
  #geom_smooth(method = "lm")+
  labs(title = "Genotype 3 (anadromous)", x="Age (years)", y=expression("Growth index"), fill="Sample")+
  scale_x_discrete(limits = c(1:10),
                  breaks=c(1:10))+
  scale_y_continuous(limits = c(100, 500)) +
  scale_fill_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 91)", "Recent (N = 22)"))+
  theme_classic()+
  plot_theme

Geno4 <- ggplot(Growthdata[Growthdata$Genotype == 4,], aes(as.factor(Lifeyear), as.numeric(GIndex), fill = Sample))+
  geom_boxplot(lwd = .5, outlier.shape = NA, width = .6, position = position_dodge(width = NULL))+
  #stat_summary(fun.data = function(x) data.frame(ymin = quantile(x, 0.025), y = median(x), ymax = quantile(x, 0.975)),
  #geom = "pointrange",  position = position_dodge(width = 0.75)) +
  #geom_smooth(method = "lm")+
  labs(title = "Genotype 4 (freshwater)", x="Age (years)", y=expression("Growth index"), fill="Sample")+
  scale_x_discrete(limits = c(1:10),
                  breaks=c(1:10))+
  scale_y_continuous(limits = c(100, 500)) +
  scale_fill_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 26)", "Recent (N = 34)"))+
  theme_classic()+
  plot_theme

VB <- readRDS("Data/Pike/VB_curve-recent-vs-historic.rds")

Genos <- ggarrange(Geno1, Geno2, Geno3, Geno4)
Genos2 <- annotate_figure(Genos, left = text_grob("Growth Index", rot = 90, size = 15),
                          bottom = text_grob("Age (years)", size = 15))

VB_Geno <- ggarrange(VB, Genos2, labels = c("A", "B"), ncol = 1)

ggsave("Figures/VB-Age-dependent-growth.png", VB_Geno, width = 16, height = 25, units = "cm", dpi = 600, bg = "white")
```

# Stomach contents

```{r stomach content cleanup recent biomass, include=FALSE, eval=FALSE}
rm(list = ls())

#Recent stomach data
stomach <- fread("Data/Pike/SC_Database.csv")

stomach$Date <- gsub("\\.", "-", stomach$Date)

stomach2 <- stomach%>%
  transmute(Date = lubridate::parse_date_time(Date, orders = c("dmy")),
            Fish_ID = Fish_ID,
            Species = case_when(Species == "S. lucioperca" ~ "Sander lucioperca",
                                Species == "P.fluviatilis" ~ "Perca fluviatilis",
                                Species == "S.erythrophthalmus" ~ "Scardinius erythrophthalmus",
                                Species == "C.harengus" ~ "Clupea harengus",
                                Species == "G.aculeatus" ~ "Gasteroseus aculeatus",
                                Species == "P.pungitius" ~ "Pungitius pungitius",
                                Species == "I.alpestris" ~ "I.alpestris",
                                Species == "Gastropoda" ~ "Gastropoda",
                                Species == "R.rutilus" ~ "Rutilus rutilus",
                                Species == "N.melanostomus" ~ "Neogobius melanostomus",
                                Species == "Isopoda" ~ "Isopoda",
                                Species == "A.aquaticus" ~ "A.aquaticus",
                                Species == "Gammarus" ~ "Gammarus",
                                Species == "E.danica" ~ "Sander lucioperca",
                                Species == "S.spinachia" ~ "Spinachia spinachia",
                                Species == "P.flesus" ~ "Platichthys flesus",
                                Species == "P.elegans" ~ "P.elegans",
                                Species == "fish larva" ~ "fish larva",
                                Species == "A.brama" ~ "Abramis brama",
                                Species == "B.bjoerkna" ~ "Blicca bjoerkna",
                                Species == "A.alburnus" ~ "Alburnus alburnus",
                                Species == "G.cernua" ~ "Gymnocephalus cernua"),
            sex = sex,
            pike_weight_g = Weight_g,
            pike_TL_mm = Total_Length_mm,
            length = prey_length_mm,
            weight = Prey_weight_g,
            stomach_weight = Stomach_weight_g,
            area = Area,
            gear = Gear)

nordic <- fread("Data/Prey/Nordic multimesh gillnets.csv")
names(nordic)[7] <- c("length")
names(nordic)[8] <- c("weight")

# binding data frames
nordic <- plyr::rbind.fill(stomach2,nordic)
str(nordic)
unique(nordic$Species)
nordic$Species <- as.factor(as.character(nordic$Species))
nordic$weight <- as.numeric(as.character(nordic$weight))
nordic$length <- as.numeric(as.character(nordic$length))

#####Rename Species because written wrong
levels(nordic$Species)[levels(nordic$Species)=="Perca fluviatilis "] <- "Perca fluviatilis"
levels(nordic$Species)[levels(nordic$Species)=="Rutilus rutilus "] <- "Rutilus rutilus"
levels(nordic$Species)[levels(nordic$Species)=="Pungitius pungitius"] <- "Pungitis pungitis"
levels(nordic$Species)[levels(nordic$Species)=="Neogobius melanostomus "] <- "Neogobius melanostomus"
levels(nordic$Species)[levels(nordic$Species)=="Spinachia spinachia"] <- "Spinachio spinachio"

#calculate missing lengths and weights
for(i in 1:nrow(nordic)){
  row.i <- nordic[i,]
  if(is.na(row.i$length)){
    mod <- mean(filter(nordic, Species == row.i$Species)$length,na.rm=TRUE)
    # Now assign calculated value into cell of original dataframe
    nordic[i,]$length <- mod
    cat(i, "done ", row.i$Species,"\n")
  }else{cat(".")}
}

nordic <- nordic%>%filter(length != "NaN")

for(i in 1:nrow(nordic)){
  row.i <- nordic[i,]
  if(is.na(row.i$weight)){
    mod <- lm(data = filter(nordic, Species == row.i$Species), log(weight) ~ log(length))
    log.weight <- predict(mod, data.frame(length = row.i$length))
    pred.weight <- 2.718281828459 ^ log.weight
    # Now assign calculated value into cell of original dataframe
    nordic[i,]$weight <- pred.weight
    cat(i, "done ", row.i$Species,"\n")
  }else{cat(".")}
}

Pike_SC <- nordic%>%filter(!is.na(Fish_ID))%>%
  transmute(Date = Date,
            fish_ID = Fish_ID,
            species = Species,
            sex = sex,
            pike_weight_g = pike_weight_g,
            pike_TL_mm = pike_TL_mm,
            prey_length_mm = length,
            prey_weight_g = weight,
            area = area)

fwrite(Pike_SC, "Data/Pike/Stomach-contents-Database-clean.csv")

Marlon_SC <- fread("Data/Pike/SC_Marlon-MA.csv")

Marlon_SC2 <- Marlon_SC%>%
  transmute(Date = Date.x,
            fish_ID = Fish_ID,
            species = Species,
            sex = NA,
            pike_weight_g = Weight,
            pike_TL_mm = Total_Length_mm,
            prey_length_mm = length,
            prey_weight_g = weight,
            area = case_when(Comparison_Area_Name == "Werderbucht" ~ "BAT",
                             Comparison_Area_Name == "Ummanz" ~ "SB",
                             Comparison_Area_Name == "Neuensiener_Selliner_See" ~ "GB"))

SC_all <- rbind(Pike_SC, Marlon_SC2)

fwrite(SC_all, "Data/Pike/Stomach-contents-recent-all.csv")

SC_clean <- SC_all %>%
  mutate(Date = as.Date(parse_date_time(Date, "ymd")),
         Species = case_when(species == "Gasteroseus aculeatus" ~ "Gasterosteus aculeatus",
                             species == "Gammerus sp." ~ "Gammarus",
                             species == "P.elegans" ~ "Palaemon adspersus",
                             species == "Pungitis pungitis" ~ "Pungitius pungitius",
                             species == "Spinachio spinachio" ~ "Spinachia spinachia",
                             TRUE ~ species),
    Prey_length_mm = prey_length_mm,
    Prey_weight_g = prey_weight_g,
    Size_class = cut(
      Prey_length_mm,
      breaks = c(0, 50, 100, 150, 200, 250, 300, Inf),
      labels = c("0–5 cm", "5–10 cm", "10–15 cm", "15–20 cm",
                 "20–25 cm", "25–30 cm", ">30 cm"),
      right = FALSE,
      include.lowest = TRUE))

SC_biomass <- SC_clean%>%
  reframe(Species,
          Prey_weight_g,
          Total_biomass_g = sum(Prey_weight_g, na.rm = T))%>%
  group_by(Species)%>%
  reframe(Species = as.factor(Species),
          Prey_weight_g = sum(Prey_weight_g, na.rm = T),
          Total_biomass_g = Total_biomass_g)%>%
  mutate(Proportion = Prey_weight_g/Total_biomass_g)%>%
  distinct()

SC_biomass2 <- SC_biomass%>%
  reframe(Origin = "recent",
          Species = as.factor(case_when(Proportion < 0.05 ~ "other",
                              TRUE ~ Species)),
          Proportion)%>%
  group_by(Species)%>%
  reframe(Proportion = sum(Proportion),
          Order = case_when(Species == "Clupea harengus" ~ 1,
                            Species == "Rutilus rutilus" ~ 2,
                            Species == "Perca fluviatilis" ~ 3,
                            Species == "Neogobius melanostomus" ~ 4,
                            Species == "Platichthys flesus" ~ 5,
                            Species == "other" ~ 6),
          Species = fct_reorder(Species, Order),
          Origin)%>%
  ungroup()%>%
  distinct()

SC_size <- SC_clean %>%
  filter(!is.na(Size_class)) %>%
  dplyr::count(Size_class, name = "prey") %>%
  mutate(Proportion = prey / sum(prey))

fwrite(SC_biomass2, "Data/Pike/Stomach_proportions_total.csv")
fwrite(SC_size, "Data/Pike/Stomach_sizes_total.csv")
```

```{r stomach content cleanup historic biomass, include=FALSE, eval=FALSE}
rm(list = ls())

# Winkler biomass data
SC_Winkler <- fread("Data/Pike/Winkler_Daten_Anteile.csv")
# Winkler size data
Winkler_preysize <- fread("Data/Pike/Winkler_Daten_Laenge.csv")

SC_Winkler <- SC_Winkler %>%
  mutate(N = case_when(Year == "1987" ~ 20,
                       Year == "1988" ~ 31,
                       Year == "1989" ~ 28,
                       Year == "1990" ~ 18,
                       Year == "2015" ~ 83))

# Biomass proportions pre - 1990, remove the ONE pike

SC_Winkler_hist <- SC_Winkler %>%
  filter(Year != "2015" & Year != "alle" & Species != "Hecht")%>%
  group_by(Species) %>%
  mutate(Percentage = Percentage*N/97) %>%
  reframe(Origin = "Winkler_past",
          Species = case_when(Species == "Tobiasfisch" ~ "other",
                              Species == "Hering" ~ "Clupea harengus",
                              Species == "Aalmutter" ~ "Zoarces viviparus",
                              Species == "Dreistachliger Stichling" ~ "other",
                              Species == "Hecht" ~ "Esox lucius",
                              Species == "Plötze" ~ "Rutilus rutilus",
                              Species == "Großer Sandaal" ~ "other",
                              Species == "Sand-/Strandgrundel" ~ "other",
                              Species == "Kaulbarsch" ~ "Gymnocephalus cernua",
                              Species == "Neunstachliger Stichling" ~ "other",
                              Species == "Barsch" ~ "Perca fluviatilis",
                              Species == "Blei" ~ "other",
                              Species == "Großer Sandaal" ~ "other",
                              Species == "Güster" ~ "other",
                              Species == "Stint" ~ "other",
                              Species == "Zander" ~ "Sander lucioperca"),
          Order = case_when(Species == "Clupea harengus" ~ 1,
                            Species == "Rutilus rutilus" ~ 2,
                            Species == "Zoarces viviparus" ~ 4,
                            Species == "Sander lucioperca" ~ 3,
                            Species == "Perca fluviatilis" ~ 7,
                            Species == "Esox lucius" ~ 5,
                            Species == "Gymnocephalus cernua" ~ 6,
                            Species == "other" ~ 8),
          Proportion = mean(Percentage))%>%
  distinct() %>%
  group_by(Species)%>%
  dplyr::mutate(Proportion = sum(Proportion)) %>%
  distinct() %>%
  ungroup() %>%
  transmute(Species = as.factor(Species), 
            Proportion = Proportion/sum(Proportion), 
            Order, Origin) %>%
  distinct()

# Biomass proportions 2015

SC_Winkler_15 <- SC_Winkler %>%
  filter(Year == "2015") %>%
  mutate(Origin = "Winkler15",
         Species = case_when(Species == "Hering" ~ "Clupea harengus",
                             Species == "Schwarzmundgrundel" ~ "other",
                             Species == "Kaulbarsch" ~ "other",
                             Species == "Barsch" ~ "other",
                             Species == "Plötze" ~ "Rutilus rutilus",
                             Species == "Zander" ~ "other"),
         Order = case_when(Species == "Clupea harengus" ~ 1,
                           Species == "Rutilus rutilus" ~ 2,
                           Species == "other" ~ 3),
         Proportion = Percentage) %>%
  distinct() %>%
  group_by(Species)%>%
  dplyr::mutate(Proportion = sum(Proportion)) %>%
  distinct() %>%
  ungroup() %>%
  transmute(Species = as.factor(Species), 
            Proportion = Proportion, 
            Order, Origin) %>%
  distinct()

# Size class assignment

Winkler_preysize2 <- Winkler_preysize %>%
  mutate(Date = as.Date(parse_date_time(Date, "dmy")),
         Size_class = cut(Prey_TL_cm,
                          breaks = c(0, 5, 10, 15, 20, 25, 30, Inf),
                          labels = c("0–5 cm", "5–10 cm", "10–15 cm", "15–20 cm",
                                     "20–25 cm", "25–30 cm", ">30 cm"),
                          right = FALSE,
                          include.lowest = TRUE))

Preysize_past <- Winkler_preysize2 %>%
  filter(year(Date) < 2015) %>%
  filter(!is.na(Size_class)) %>%
  dplyr::count(Size_class, name = "prey") %>%
  mutate(Proportion = prey / sum(prey))

Preysize_15 <- Winkler_preysize2 %>%
  filter(year(Date) == 2015) %>%
  filter(!is.na(Size_class)) %>%
  dplyr::count(Size_class, name = "prey") %>%
  mutate(Proportion = prey / sum(prey))

fwrite(SC_Winkler_hist, "Data/Pike/Stomach-proportions-past.csv")
fwrite(SC_Winkler_15, "Data/Pike/Stomach-proportions-15.csv")
fwrite(Preysize_past, "Data/Pike/Preysize-proportions-past.csv")
fwrite(Preysize_15, "Data/Pike/Preysize-proportions-15.csv")
```

```{r stomach content cleanup frequency, include=FALSE, eval=FALSE}
rm(list = ls())

#read in data

SC_all <- fread("Data/Pike/Stomach-contents-recent-all.csv")
SC_all <- SC_all %>% filter(pike_TL_mm > 400)

Winkler_preysize <- fread("Data/Pike/Winkler_Daten_Laenge.csv")

Winkler_preysize_past <- Winkler_preysize %>%
  mutate(Year = year(as.Date(parse_date_time(Date, "dmy")))) %>%
  filter(Year < 2015)

Winkler_preysize_15 <- Winkler_preysize %>%
  mutate(Year = year(as.Date(parse_date_time(Date, "dmy")))) %>%
  filter(Year == 2015)

#Dummy IDs for historic dataset

Winkler_preysize_past <- Winkler_preysize_past %>%
  dplyr::mutate(Pike_ID = paste(Date, Pike_TL_cm, sep = "_"))

Winkler_preysize_15 <- Winkler_preysize_15 %>%
  dplyr::mutate(Pike_ID = paste(Date, Pike_TL_cm, sep = "_"))

#Harmonise species across data sets

recent_species_map <- c(
  "Perca fluviatilis"      = "P. fluviatilis",
  "Clupea harengus"        = "C. harengus",
  "Rutilus rutilus"        = "R. rutilus",
  "Neogobius melanostomus" = "N. melanostomus",
  "Sander lucioperca"      = "S. lucioperca",
  "Platichthys flesus"     = "P. flesus",
  "Gymnocephalus cernua"   = "G. cernua",
  "Gasterosteus aculeatus" = "G. aculeatus",
  "Gasteroseus aculeatus"  = "G. aculeatus",
  "Pungitis pungitis"      = "P. pungitius"
)

winkler_species_map <- c(
  "C.harengus"     = "C. harengus",
  "R.rutilus"      = "R. rutilus",
  "P.fluviatilis"  = "P. fluviatilis",
  "S.lucioperca"   = "S. lucioperca",
  "N.melanostomus" = "N. melanostomus",
  "G.cernua"       = "G. cernua",
  "G.aculeatus"    = "G. aculeatus",
  "A.tobianus"     = "A. tobianus",
  "O.eperlanus"    = "O. eperlanus",
  "Z.vivparus"     = "Z. viviparus",
  "A.brama"        = "A. brama",
  "E.lucius"       = "E. lucius"
)

SC_all <- SC_all %>%
  dplyr::mutate(Species_raw = dplyr::if_else(species %in% names(recent_species_map),
                                              recent_species_map[species], species))

Winkler_preysize_past <- Winkler_preysize_past %>%
  dplyr::mutate(Species_raw = dplyr::if_else(Prey_spec %in% names(winkler_species_map),
                                              winkler_species_map[Prey_spec], Prey_spec))

Winkler_preysize_15 <- Winkler_preysize_15 %>%
  dplyr::mutate(Species_raw = dplyr::if_else(Prey_spec %in% names(winkler_species_map),
                                              winkler_species_map[Prey_spec], Prey_spec))

n_pike_recent <- n_distinct(SC_all$fish_ID)
n_pike_past   <- n_distinct(Winkler_preysize_past$Pike_ID)
n_pike_15     <- n_distinct(Winkler_preysize_15$Pike_ID)

#%Frequency of occurrence with a 5% cutoff
#"Other" = share of individuals carrying one or more rare species that occurr in less than 5% of stomachs

build_FO_table <- function(df, ind_col, species_col, n_pike, cutoff = 0.05) {
  ind_species <- df %>% dplyr::distinct(.data[[ind_col]], .data[[species_col]])

  FO_raw <- ind_species %>%
    dplyr::count(.data[[species_col]], name = "n_ind") %>%
    dplyr::mutate(Proportion = n_ind / n_pike)

  common <- FO_raw %>% dplyr::filter(Proportion >= cutoff) %>% dplyr::pull(.data[[species_col]])

  FO_common <- FO_raw %>%
    dplyr::filter(.data[[species_col]] %in% common) %>%
    dplyr::rename(Species = !!species_col)

  n_other <- ind_species %>%
    dplyr::filter(!(.data[[species_col]] %in% common)) %>%
    dplyr::distinct(.data[[ind_col]]) %>%
    nrow()

  dplyr::bind_rows(
    FO_common,
    tibble::tibble(Species = "Other", n_ind = n_other, Proportion = n_other / n_pike)
  ) %>%
    dplyr::arrange(dplyr::desc(Proportion))
}

Prey_FO_recent <- build_FO_table(SC_all, "fish_ID", "Species_raw", n_pike_recent)
Prey_FO_past   <- build_FO_table(Winkler_preysize_past, "Pike_ID", "Species_raw", n_pike_past)
Prey_FO_15     <- build_FO_table(Winkler_preysize_15, "Pike_ID", "Species_raw", n_pike_15)

# --- Shared colour lookup, built once from the union of species across all 3 periods ---
all_common_species <- sort(unique(c(
  setdiff(Prey_FO_recent$Species, "Other"),
  setdiff(Prey_FO_past$Species, "Other"),
  setdiff(Prey_FO_15$Species, "Other")
)))

palette_colors <- khroma::colour("discrete rainbow")(length(all_common_species))
species_colors <- setNames(as.character(palette_colors), all_common_species)
species_colors["Other"] <- "grey60"

saveRDS(species_colors, "Data/Prey/Species-cols.rds")

Prey_FO_recent <- Prey_FO_recent %>% dplyr::mutate(Species = factor(Species, levels = names(species_colors)))
Prey_FO_past   <- Prey_FO_past   %>% dplyr::mutate(Species = factor(Species, levels = names(species_colors)))
Prey_FO_15     <- Prey_FO_15     %>% dplyr::mutate(Species = factor(Species, levels = names(species_colors)))

# --- Order bars by descending contribution within each panel, "Other" always last ---
order_by_contribution <- function(df) {
  df %>%
    dplyr::mutate(Species = as.character(Species)) %>%
    dplyr::arrange(Species == "Other", dplyr::desc(Proportion)) %>%
    dplyr::mutate(Species = factor(Species, levels = unique(Species)))
}

Prey_FO_recent <- order_by_contribution(Prey_FO_recent)
Prey_FO_past   <- order_by_contribution(Prey_FO_past)
Prey_FO_15     <- order_by_contribution(Prey_FO_15)

# --- Bar charts ---
FO_recent <- ggplot(Prey_FO_recent, aes(Species, Proportion, fill = Species)) +
  geom_col() +
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), vjust = -0.4, size = 2.5) +
  scale_fill_manual(values = species_colors, drop = TRUE) +
  scale_y_continuous(labels = scales::percent, expand = expansion(mult = c(0, 0.15))) +
  labs(title = "Prey frequency of occurrence (%)", x = NULL, y = "% of individuals") +
  theme_classic() +
  theme(plot.title = element_text(size = 10, colour = "transparent"),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        legend.position = "none")

FO_past <- ggplot(Prey_FO_past, aes(Species, Proportion, fill = Species)) +
  geom_col() +
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), vjust = -0.4, size = 2.5) +
  scale_fill_manual(values = species_colors, drop = TRUE) +
  scale_y_continuous(labels = scales::percent, expand = expansion(mult = c(0, 0.15))) +
  labs(title = "Prey frequency of occurrence (%)", x = NULL, y = "% of individuals") +
  theme_classic() +
  theme(plot.title = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        legend.position = "none")

FO_15 <- ggplot(Prey_FO_15, aes(Species, Proportion, fill = Species)) +
  geom_col() +
  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), vjust = -0.4, size = 2.5) +
  scale_fill_manual(values = species_colors, drop = TRUE) +
  scale_y_continuous(labels = scales::percent, expand = expansion(mult = c(0, 0.15))) +
  labs(title = "Prey frequency of occurrence (%)", x = NULL, y = "% of individuals") +
  theme_classic() +
  theme(plot.title = element_text(size = 10, colour = "transparent"),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        legend.position = "none")

# --- Size / length histograms (unchanged) ---
Sizes_past <- ggplot(Winkler_preysize_past) +
  geom_histogram(aes(Prey_TL_cm)) +
  scale_x_continuous(limits = c(0, 51)) +
  labs(title = "Prey size distribution",
       x = "Standard length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_past$Prey_TL_cm),
             colour = "red", linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Sizes_15 <- ggplot(Winkler_preysize_15) +
  geom_histogram(aes(Prey_TL_cm)) +
  scale_x_continuous(limits = c(0, 51)) +
  labs(title = "Prey size distribution",
       x = "Standard length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_15$Prey_TL_cm), colour = "red",
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Sizes_recent <- ggplot(SC_all) +
  geom_histogram(aes(prey_length_mm/10)) +
  scale_x_continuous(limits = c(0, 51)) +
  labs(title = "Prey size distribution",
       x = "Standard length (cm)") +
  geom_vline(xintercept = mean(SC_all$prey_length_mm/10), colour = "red",
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Hist_past <- ggplot(Winkler_preysize_past) +
  geom_histogram(aes(Pike_TL_cm)) +
  scale_x_continuous(limits = c(0, 125)) +
  labs(title = "Pike size distribution",
       x = "Total length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_past$Pike_TL_cm), colour = "red",
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Hist_15 <- ggplot(Winkler_preysize_15) +
  geom_histogram(aes(Pike_TL_cm)) +
  scale_x_continuous(limits = c(0, 125)) +
  labs(title = "Pike size distribution",
       x = "Total length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_15$Pike_TL_cm), colour = "red",
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Hist_recent <- ggplot(SC_all) +
  geom_histogram(aes(pike_TL_mm/10)) +
  scale_x_continuous(limits = c(0, 125)) +
  labs(title = "Pike size distribution",
       x = "Total length (cm)") +
  geom_vline(xintercept = mean(SC_all$pike_TL_mm/10, na.rm = TRUE), colour = "red",
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

# --- Combine per period ---
Past <- ggarrange(FO_past, Sizes_past, Hist_past, nrow = 1)
Past1 <- annotate_figure(Past, top = text_grob("1987 - 1990 (N = 97)", size = 12, color = "black"))

Year15 <- ggarrange(FO_15, Sizes_15, Hist_15, nrow = 1)
Year15.1 <- annotate_figure(Year15, top = text_grob("Spring 2015 (N = 83)", size = 12, color = "black"))

Recent <- ggarrange(FO_recent, Sizes_recent, Hist_recent, nrow = 1)
Recent1 <- annotate_figure(Recent, top = text_grob("2019 - 2022 (N = 171)", size = 12, color = "black"))

# --- Legend (species -> colour taken directly from the shared lookup) ---
dummy_data1 <- data.frame(
  Species = factor(names(species_colors), levels = names(species_colors)),
  x = seq_along(species_colors),
  y = seq_along(species_colors)
)

legend_plot1 <- ggplot(dummy_data1, aes(x = x, y = y, colour = Species)) +
  geom_point(size = 3) +
  scale_colour_manual(values = species_colors, breaks = names(species_colors)) +
  guides(colour = guide_legend(title = "Species", ncol = 3)) +
  theme_void()

legend1 <- cowplot::get_legend(legend_plot1)

SCA_figure <- cowplot::plot_grid(Past1, Year15.1, Recent1,
                                  labels = c("A", "B", "C"),
                                  nrow = 3, ncol = 1)

ggsave("Figures/Stomach-contents-Freq-Ocurr.png", SCA_figure, width = 25, height = 20, units = "cm", dpi = 600, bg = "white")
```


```{r stomach content biomass graphics, include=FALSE, eval=FALSE}
rm(list = ls())

#raw data
SC_all <- fread("Data/Pike/Stomach-contents-recent-all.csv")

#filter out smallies
SC_all <- SC_all %>% filter(pike_TL_mm > 400)

Winkler_preysize <- fread("Data/Pike/Winkler_Daten_Laenge.csv")


Winkler_preysize_past <- Winkler_preysize %>%
  mutate(Year = year(as.Date(parse_date_time(Date, "dmy")))) %>%
           filter(Year < 2015)

Winkler_preysize_15 <- Winkler_preysize %>%
  mutate(Year = year(as.Date(parse_date_time(Date, "dmy")))) %>%
           filter(Year == 2015)

# Proportions
Prey_biomass_recent <- fread("Data/Pike/Stomach_proportions_total.csv")
Prey_biomass_past <- fread("Data/Pike/Stomach-proportions-past.csv")
Prey_biomass_15 <- fread("Data/Pike/Stomach-proportions-15.csv")
Prey_size_recent <- fread("Data/Pike/Stomach_sizes_total.csv")
Prey_size_past <- fread("Data/Pike/Preysize-proportions-past.csv")
Prey_size_15 <- fread("Data/Pike/Preysize-proportions-15.csv")

  
Prey_biomass_recent$Species <- reorder(Prey_biomass_recent$Species, Prey_biomass_recent$Order)
Prey_biomass_past$Species <- reorder(Prey_biomass_past$Species, Prey_biomass_past$Order)
Prey_biomass_15$Species <- reorder(Prey_biomass_15$Species, Prey_biomass_15$Order)

Prey_biomass_recent2 <- Prey_biomass_recent %>%
  arrange(Order) %>%
  mutate(csum = rev(cumsum(rev(Proportion))),
           pos1 = Proportion/2 + lead(csum, 1),
           pos = case_when(is.na(pos1) == TRUE ~ Proportion/2,
                           TRUE ~ pos1))

Prey_biomass_past2 <- Prey_biomass_past %>%
  arrange(Order) %>%
  mutate(csum = rev(cumsum(rev(Proportion))),
           pos1 = Proportion/2 + lead(csum, 1),
           pos = case_when(is.na(pos1) == TRUE ~ Proportion/2,
                           TRUE ~ pos1))

Prey_biomass_15.2 <- Prey_biomass_15 %>%
  arrange(Order) %>%
  mutate(csum = rev(cumsum(rev(Proportion))),
           pos1 = Proportion/2 + lead(csum, 1),
           pos = case_when(is.na(pos1) == TRUE ~ Proportion/2,
                           TRUE ~ pos1))

Prey_size_recent2 <- Prey_size_recent %>%
  dplyr::mutate(order = rev(row_number()))%>%
  arrange(order) %>%
  mutate(csum = rev(cumsum(rev(Proportion))),
         label_text = percent(Proportion, accuracy = 0.1),
           pos1 = Proportion/2 + lead(csum, 1),
           pos = case_when(is.na(pos1) == TRUE ~ Proportion/2,
                           TRUE ~ pos1))

Prey_size_past2 <- Prey_size_past %>%
  dplyr::mutate(order = rev(row_number()))%>%
  arrange(order) %>%
  mutate(csum = rev(cumsum(rev(Proportion))),
         label_text = percent(Proportion, accuracy = 0.1),
           pos1 = Proportion/2 + lead(csum, 1),
           pos = case_when(is.na(pos1) == TRUE ~ Proportion/2,
                           TRUE ~ pos1))

Prey_size_15.2 <- Prey_size_15 %>%
  dplyr::mutate(order = rev(row_number()))%>%
  arrange(order) %>%
  mutate(csum = rev(cumsum(rev(Proportion))),
         label_text = percent(Proportion, accuracy = 0.1),
           pos1 = Proportion/2 + lead(csum, 1),
           pos = case_when(is.na(pos1) == TRUE ~ Proportion/2,
                           TRUE ~ pos1))

Biomass_recent <- ggplot(Prey_biomass_recent2, aes(x = "", y = Proportion, fill = as.factor(Order))) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +  # Convert to a polar coordinate for pie chart
  geom_label_repel(aes(y = pos, label = scales::percent(Proportion)), nudge_x = .75, 
                   size = 2, show.legend = FALSE, fill = "white")+
  labs(title = "Prey biomass proportion (%)") +
  scale_fill_viridis_d(alpha = 0.9)+
  theme_void()+
  theme(plot.title = element_text(size = 10, color = "transparent"),
        legend.position = "none")+
  scale_fill_manual(breaks = c(1, 2, 3, 4, 5, 6), 
                    values = c("#1B9E77", "#66A61E", "#D95F02", "cyan", "#E7298A", "blue"))

Biomass_past <- ggplot(Prey_biomass_past2, aes(x = "", y = Proportion, fill = as.factor(Order))) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +  # Convert to a polar coordinate for pie chart
  geom_label_repel(aes(y = pos, label = scales::percent(Proportion, accuracy = 0.1)), nudge_x = .75, 
                   size = 2, show.legend = FALSE, fill = "white")+
  labs(title = "Prey biomass proportion (%)") +
  scale_fill_viridis_d(alpha = 0.9)+
  theme_void()+
  theme(plot.title = element_text(size = 10, color = "black"),
        legend.position = "none")+
  scale_fill_manual(breaks = c(1, 2, 3, 4, 6, 7, 8), 
                    values = c("#1B9E77", "#66A61E","#A6761D", "#7570B3", "#E6AB02", "#D95F02", "blue"))

Biomass_15 <- ggplot(Prey_biomass_15.2, aes(x = "", y = Proportion, fill = as.factor(Order))) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +  # Convert to a polar coordinate for pie chart
  geom_label_repel(aes(y = pos, label = scales::percent(Proportion/100)), nudge_x = .75, 
                   size = 2, show.legend = FALSE, fill = "white")+
  labs(title = "Prey biomass proportion (%)") +
  scale_fill_viridis_d(alpha = 0.9)+
  theme_void()+
  theme(plot.title = element_text(size = 10, color = "transparent"),
        legend.position = "none")+
  scale_fill_manual(breaks = c(1, 2, 3, 4, 5, 6), 
                    values = c("#1B9E77", "#66A61E", "blue"))

Sizes_past <- ggplot(Winkler_preysize_past) +
  geom_histogram(aes(Prey_TL_cm)) +
  scale_x_continuous(limits = c(0, 51)) +
  labs(title = "Prey size distribution",
       x = "Standard length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_past$Prey_TL_cm), 
             colour = "red", linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "black"),,
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Sizes_15 <- ggplot(Winkler_preysize_15) +
  geom_histogram(aes(Prey_TL_cm)) +
  scale_x_continuous(limits = c(0, 51)) +
  labs(title = "Prey size distribution",
       x = "Standard length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_15$Prey_TL_cm), colour = "red", 
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),,
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Sizes_recent <- ggplot(SC_all) +
  geom_histogram(aes(prey_length_mm/10)) +
  scale_x_continuous(limits = c(0, 51)) +
  labs(title = "Prey size distribution",
       x = "Standard length (cm)") +
  geom_vline(xintercept = mean(SC_all$prey_length_mm/10), colour = "red", 
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),,
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Hist_past <- ggplot(Winkler_preysize_past) +
  geom_histogram(aes(Pike_TL_cm)) +
  scale_x_continuous(limits = c(0, 125)) +
  labs(title = "Pike size distribution",
       x = "Total length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_past$Pike_TL_cm), colour = "red", 
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "black"),,
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Hist_15 <- ggplot(Winkler_preysize_15) +
  geom_histogram(aes(Pike_TL_cm)) +
    scale_x_continuous(limits = c(0, 125)) +
  labs(title = "Pike size distribution",
       x = "Total length (cm)") +
  geom_vline(xintercept = mean(Winkler_preysize_15$Pike_TL_cm), colour = "red", 
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Hist_recent <- ggplot(SC_all) +
  geom_histogram(aes(pike_TL_mm/10)) +
    scale_x_continuous(limits = c(0, 125)) +
  labs(title = "Pike size distribution",
       x = "Total length (cm)") +
  geom_vline(xintercept = mean(SC_all$pike_TL_mm/10, na.rm = TRUE), colour = "red", 
             linetype = "dotted", linewidth = 1) +
  theme_classic() +
  theme(plot.title = element_text(size = 10, color = "transparent"),,
        axis.title = element_text(size = 10, color = "black"),
        axis.text = element_text(size = 10, color = "black"))

Past <- ggarrange(Biomass_past, Sizes_past, Hist_past, nrow = 1)
Past1 <- annotate_figure(Past, top = text_grob("1987 - 1990 (N = 97)", size = 12, color = "black"))

Year15 <- ggarrange(Biomass_15, Sizes_15, Hist_15, nrow = 1)
Year15.1 <- annotate_figure(Year15, top = text_grob("Spring 2015 (N = 83)", size = 12, color = "black"))

Recent <- ggarrange(Biomass_recent, Sizes_recent, Hist_recent, nrow = 1)
Recent1 <- annotate_figure(Recent, top = text_grob("2019 - 2022 (N = 171)", size = 12, color = "black"))


#Dummy data for plotting
species_colors <- c("C. harengus" = "#1B9E77", "R. rutilus" = "#66A61E", "P. fluviatilis" = "#D95F02", "Z. viviparus" = "#7570B3", "P. flesus" = "#E7298A", 
                    "G. cernua" = "#E6AB02", "N. melanostomus" = "cyan", "S. lucioperca" = "#A6761D", "Other" = "blue")

# Dummy datasets
dummy_data1 <- data.frame(
  species = names(species_colors),
  x = 1:length(species_colors),
  y = 1:length(species_colors)
)

# Dummy plot for legend
legend_plot1 <- ggplot(dummy_data1, aes(x = x, y = y, color = species)) +
  geom_point(size = 3) +
  scale_color_manual(breaks = names(species_colors), values = species_colors) +
  guides(color = guide_legend(title = "Species", ncol = 3)) +
  theme_void()  # Remove axes and gridlines

legend1 <- cowplot::get_legend(legend_plot1)


SCA_figure <- cowplot::plot_grid(Past1, Year15.1, Recent1, legend1,
                  labels = c("A", "B", "C"),
                  nrow = 4, ncol = 1)

ggsave("Figures/Stomach-contents-all.png", SCA_figure, width = 20, height = 20, units = "cm", dpi = 600, bg = "white")
```

```{r figures predator-prey size relationship, include=FALSE, eval=FALSE}
rm(list = ls())

#raw data
SC_all <- fread("Data/Pike/Stomach-contents-recent-all.csv")
Winkler_preysize <- fread("Data/Pike/Winkler_Daten_Laenge.csv")


Winkler_preysize_past <- Winkler_preysize %>%
  mutate(Year = year(as.Date(parse_date_time(Date, "dmy")))) %>%
           filter(Year < 2015)

Winkler_preysize_15 <- Winkler_preysize %>%
  mutate(Year = year(as.Date(parse_date_time(Date, "dmy")))) %>%
           filter(Year == 2015)

#join them

SC_join <- SC_all %>%
  transmute(Sample = "Recent",
            Preysize = prey_length_mm/10,
            Pikesize = pike_TL_mm)

Winkler_join <- Winkler_preysize %>%
  transmute(Sample = case_when(year(as.Date(parse_date_time(Date, "dmy"))) < 2015 ~ "Spring 2015",
                               TRUE ~ "Historic"),
            Preysize = Prey_TL_cm,
            Pikesize = Pike_TL_cm)

Preysize_all <- rbind(SC_join, Winkler_join)

mod <- lm(Preysize ~ Pikesize * Sample, data = Preysize_all)
anova(mod)
summary(mod)
emtrends(mod, pairwise ~ Sample, var = "Pikesize")

Sizerelation <- ggplot()+
  geom_point(data = SC_all, aes(pike_TL_mm/10, prey_length_mm/10, colour = "Recent"))+
  geom_point(data = Winkler_preysize_past, aes(Pike_TL_cm, Prey_TL_cm,colour = "Past"))+
  geom_point(data = Winkler_preysize_15, aes(Pike_TL_cm, Prey_TL_cm, colour = "Spring 2015"))+
  geom_smooth(data = SC_all, aes(pike_TL_mm/10, prey_length_mm/10,colour = "Recent", fill = "Recent"), method = "lm")+
  geom_smooth(data = Winkler_preysize_past, aes(Pike_TL_cm,Prey_TL_cm, colour = "Past", fill = "Past"), method = "lm")+
  geom_smooth(data = Winkler_preysize_15, aes(Pike_TL_cm, Prey_TL_cm,  colour = "Spring 2015", fill = "Spring 2015"), method = "lm")+
  labs(x = "Pike total length (cm)",
       y = "Prey standard length (cm)",
       fill = "Sample",
       colour = "Sample")+
  scale_y_continuous(breaks = seq(0, 55, 5))+
  scale_x_continuous(limits = c(40, 130), breaks = seq(0, 125, 10))+
  scale_color_manual(breaks = c("Recent", "Past", "Spring 2015"), values = c("#C5D86D", "#00BFB2", "#004643"), labels = c("2019 - 2022", "1987 - 1990", "Spring 2015"))+
  scale_fill_manual(breaks = c("Recent", "Past", "Spring 2015"), values = c("#C5D86D", "#00BFB2", "#004643"), labels = c("2019 - 2022", "1987 - 1990", "Spring 2015"))+
  theme_classic()+
  theme(panel.grid.major = element_line(colour = "grey"),
        axis.title = element_text(size = 15, colour = "black"),
        axis.text = element_text(size = 15, colour = "black"),
        legend.text = element_text(size = 15, colour = "black"),
        legend.title = element_text(size = 15, colour = "black"),
        legend.position = "bottom")

ggsave("Figures/Predator-prey-length.png", Sizerelation, width = 16, height = 12, units = "cm", dpi = 600, bg = "white")

```

# Prey fish biomass, cormorants and other disasters

```{r cormorant time series}
rm(list = ls())

# --- Kormoran-Daten & Bodden-Zentroide ---
cormorant_bycolony <- read_excel("Data/Environment/Timeseries/Cormorant_data/cormorants_geo.xlsx", sheet = "zaehldaten")
cormorant_geo <- read_excel("Data/Environment/Timeseries/Cormorant_data/cormorants_geo.xlsx", sheet = "geo") %>%
  st_as_sf(coords = c("lon", "lat"), crs = "+proj=longlat +datum=WGS84")

sf::sf_use_s2(FALSE)

bodden_shape <- st_read("Data/Environment/Timeseries/Cormorant_data/mv_fishery_fanggebiete.shp", quiet = TRUE) %>%
  st_transform(crs = "+proj=longlat +datum=WGS84") %>%
  dplyr::filter(gewässerc %in% c("1", "2", "3", "4", "5a", "5b", "6", "8a", "8b")) %>%
  dplyr::mutate(Gebiet = dplyr::case_when(gewässerc == "1" ~ "Stettiner Haff",
                            gewässerc == "2" ~ "Peenestrom",
                            gewässerc == "3" ~ "Greifswalder Bodden",
                            gewässerc == "4" ~ "Kubitzer Bodden und Strelasund",
                            gewässerc %in% c("5a", "5b") ~ "Westrügen und Gr. Jasmunder Bodden",
                            gewässerc == "6" ~ "Kl. Jasmunder Bodden",
                            gewässerc == "8a" ~ "Darß-Zingster Bodden West",
                            gewässerc == "8b" ~ "Darß-Zingster Bodden Ost",
                            TRUE ~ gewässerc)) %>%
  dplyr::group_by(Gebiet) %>%
  dplyr::summarize(geometry = st_union(geometry))

bodden_cent <- st_centroid(bodden_shape)

# --- Distanzmatrix: Kolonie <-> Bodden-Zentroid ---
distmat <- st_distance(bodden_cent, cormorant_geo) %>% tibble::as_tibble()
names(distmat) <- cormorant_geo$colony
distmat$Gebiet <- bodden_cent$Gebiet

distlong <- distmat %>%
  tidyr::pivot_longer(cols = -Gebiet, values_to = "distance")

# --- Distanzgewichteter Kormoran-Index je Gebiet & Jahr ---
comorants_dist_weighted <- cormorant_bycolony %>%
  tidyr::pivot_longer(cols = -year) %>%
  dplyr::mutate(value = as.numeric(value)) %>%
  na.omit() %>%
  dplyr::left_join(distlong %>% dplyr::mutate(distance = as.numeric(distance)), by = "name") %>%
  dplyr::group_by(year, Gebiet) %>%
  dplyr::mutate(cormorants_weighted = sum(value / ((distance / 1000)^2))) %>%
  dplyr::filter(!is.na(Gebiet)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(year, Gebiet) %>%
  dplyr::summarize(cormorants_weighted = mean(cormorants_weighted), .groups = "drop") %>%
  dplyr::arrange(Gebiet, year) %>%
  dplyr::mutate(year = factor(year, levels = seq(1952, 2022, 1)),
         Gebiet = factor(Gebiet)) %>%
  tidyr::complete(year, Gebiet)

comorants_dist_final <- comorants_dist_weighted %>%
  ungroup()%>%
  dplyr::bind_rows(comorants_dist_weighted %>%
              dplyr::filter(Gebiet == "Darß-Zingster Bodden Ost") %>%
              dplyr::group_by(year) %>%
              dplyr::summarise(cormorants_weighted = mean(cormorants_weighted), .groups = "drop") %>%
              dplyr::mutate(Gebiet = "Darß-Zingster Bodden Ost"))

fwrite(comorants_dist_final, "Data/Environment/Timeseries/Cormorant_data/comorants_dist_weighted.csv")
```

```{r trawl data analysis, include=FALSE, eval=FALSE}
rm(list = ls())

# Trawl data Barther Bodden, abundance/biomass per hectar, juvenile and small fish up to 10 cm TL, 5 mm mesh size
Trawls <- fread("Data/Prey/Trawldata_1983-2013.CSV")
cormorants_dist_final <- fread("Data/Environment/Timeseries/Cormorant_data/comorants_dist_weighted.csv")

cols_to_scale <- c(4:28)
Trawls[, (cols_to_scale) := lapply(.SD, scale), .SDcols = cols_to_scale]

# basic linear model
lm_mod <- lm(Biomass_per_ha ~ Year, data = Trawls)

# segmented model (with initial guess)
seg_mod <- segmented(lm_mod, seg.Z = ~Year, psi = list(Year = 1995))
summary(seg_mod)
seg_mod$psi

plot(Trawls$Year, Trawls$Biomass_per_ha, pch = 16)
plot(seg_mod, add = TRUE, col = "red")

bp <- breakpoints(Biomass_per_ha ~ Year, data = Trawls)
summary(bp)

breakpoints(bp)
Trawls$Year[breakpoints(bp)$breakpoints]

# Biomass
bp_bio <- breakpoints(Biomass_per_ha ~ Year, data = Trawls)

# Abundance
bp_ind <- breakpoints(Ind_ha ~ Year, data = Trawls)

Trawls$Year[breakpoints(bp_bio)$breakpoints]
Trawls$Year[breakpoints(bp_ind)$breakpoints]

# --- plot data prep ---
plot_cols1 <- c("Biomass_per_ha")
plot_cols2 <- c(
  "C.harengus", 
  "R.rutilus", 
  "P.fluviatilis", 
  "P.flesus", 
  "G.cernua", 
  "O.eperlanus", 
  "N.melanostomus", 
  "S.lucioperca", 
  "G.aculeatus", 
  "P.pungitius"
  )

Trawls_long1 <- melt(Trawls, id.vars = "Year", measure.vars = plot_cols1, variable.name = "Variable", value.name = "z")
Trawls_long2 <- melt(Trawls, id.vars = "Year", measure.vars = plot_cols2, variable.name = "Variable", value.name = "z")

# --- Kormoran-Index für das Trawl-Gebiet (Datenaufbereitung siehe Cormorant-Chunk) ---
cormorant_index <- cormorants_dist_final %>%
  dplyr::filter(Gebiet == "Darß-Zingster Bodden Ost") %>%
  dplyr::mutate(Year = as.numeric(as.character(year))) %>%
  dplyr::select(Year, cormorants_weighted) %>%
  dplyr::filter(!is.na(cormorants_weighted))

trawl_year_range <- range(Trawls_long1$Year, na.rm = TRUE)
cormorant_index <- cormorant_index %>%
  dplyr::filter(Year >= trawl_year_range[1], Year <= trawl_year_range[2])

biomass_range   <- range(Trawls_long1$z, na.rm = TRUE)
cormorant_range <- range(cormorant_index$cormorants_weighted, na.rm = TRUE)

scale_factor <- diff(biomass_range) / diff(cormorant_range)
scale_offset <- biomass_range[1] - cormorant_range[1] * scale_factor

# --- Trawlplot1: Biomass (kg/ha) + Kormoran-Index (2. y-Achse) ---
Trawlplot1 <- ggplot(Trawls_long1, aes(x = Year, y = z, colour = Variable)) +
  geom_point(alpha = 0.6, size = 1) +
  geom_smooth(method = "loess", se = TRUE, linewidth = 0.8) +
  geom_vline(xintercept = 1989, linetype = "dashed", colour = "red", linewidth = 0.8) +
  geom_line(data = cormorant_index,
            aes(x = Year, y = cormorants_weighted * scale_factor + scale_offset),
            inherit.aes = FALSE, colour = "black", linewidth = 0.8) +
  coord_cartesian(ylim = c(0, NA)) +
  scale_y_continuous(
    sec.axis = sec_axis(~ (. - scale_offset) / scale_factor,
                         name = "Cormorant index (distance-weighted)")
  ) +
  scale_colour_manual(values = c("Biomass_per_ha" = "darkred")) +
  theme_classic() +
  labs(x = "Year", y = "Total biomass (kg/ha)") +
  theme(legend.position = "none",
        panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.5),
        plot.title = element_text(size = 10, colour = "black"),
        axis.text.y.left = element_text(size = 10, colour = "darkred"),
        axis.title.y.left = element_text(size = 10, colour = "darkred"),
        axis.line.y.left = element_line(colour = "darkred"),
        axis.ticks.y.left = element_line(colour = "darkred"),
        axis.text.y.right = element_text(size = 10, colour = "black"),
        axis.title.y.right = element_text(size = 10, colour = "black"),
        axis.line.y.right = element_line(colour = "black"))

species_colors <- readRDS("Data/Prey/Species-cols.rds")

species_name_lookup <- c(
  "C.harengus"     = "C. harengus",
  "R.rutilus"      = "R. rutilus",
  "P.fluviatilis"  = "P. fluviatilis",
  "P.flesus"       = "P. flesus",
  "G.cernua"       = "G. cernua",
  "N.melanostomus" = "N. melanostomus",
  "S.lucioperca"   = "S. lucioperca",
  "G.aculeatus"    = "G. aculeatus",
  "A.tobianus"     = "A. tobianus",
  "O.eperlanus"    = "O. eperlanus",
  "P.pungitius"    = "P. pungitius"
)

Trawls_long2 <- Trawls_long2 %>%
  dplyr::mutate(Variable = dplyr::recode(as.character(Variable), !!!species_name_lookup))

# --- Trawlplot2: species abundances (z-scored) ---
Trawlplot2 <- ggplot(Trawls_long2, aes(x = Year, y = z, colour = Variable)) +
  geom_point(alpha = 0.6, size = 1) +
  geom_smooth(method = "loess", se = TRUE, linewidth = 0.8) +
  facet_wrap(~ Variable, scales = "free_y") +
  scale_colour_manual(values = species_colors) +
  theme_classic() +
  labs(x = "Year", y = "z-scored abundance (Ind/ha)") +
  theme(legend.position = "none",
        panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.5),
        plot.title = element_text(size = 10, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title = element_text(size = 10, colour = "black"))

Trawlfig <- cowplot::plot_grid(Trawlplot1, Trawlplot2, ncol = 1)

ggsave("Figures/Trawldata.png", Trawlfig, width = 16, height = 20, units = "cm", dpi = 600, bg = "white")
```

```{r landings figure for appendix, include=FALSE, eval=FALSE}
rm(list = ls())

Landings <- fread("Data/Environment/Timeseries/Orig_fishery_data/all_species_catch_1976-2018.csv", encoding = "Latin-1")

species_name_lookup2 <- c(
  "Hering"     = "C. harengus",
  "Plï¿½tze"     = "R. rutilus",
  "Barsch"     = "P. fluviatilis",
  "Kaulbarsch" = "G. cernua",
  "Zander"     = "S. lucioperca"
)

Landings_darss <- Landings %>%
  dplyr::filter(area == "Darsser Boddenkette",
                species %in% names(species_name_lookup2)) %>%
  dplyr::mutate(Species = dplyr::recode(species, !!!species_name_lookup2))

species_colors <- readRDS("Data/Prey/Species-cols.rds")

Landingsplot <- ggplot(Landings_darss, aes(x = year, y = catch, colour = Species)) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1) +
  facet_wrap(~ Species, scales = "free_y") +
  scale_colour_manual(values = species_colors) +
  theme_classic() +
  labs(x = "Year", y = "Landings") +
  theme(legend.position = "none",
        panel.grid.major.y = element_line(colour = "lightgrey", linewidth = 0.5),
        plot.title = element_text(size = 10, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title = element_text(size = 10, colour = "black"))

ggsave("Figures/Landings_Darsser-Boddenkette.png", Landingsplot, width = 16, height = 12, units = "cm", dpi = 600, bg = "white")
```


# Isotope analysis

```{r stratified sampling, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Historic_pike_master.csv")

set.seed(123)

Pikemaster2 <- Pikemaster%>%
  mutate(Size_class = cut(Total_Length_mm, breaks = seq(0, 125, by = 25)))

Sample <- Pikemaster2%>%
  group_by(Waterbody, Size_class, Genotype)%>%
  sample_n(5, replace = TRUE)%>%
  ungroup()%>%
  distinct()

fwrite(Sample, "Data/Pike/Historic_pike_SI-sample.csv")
```

```{r correction factor pike, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")

Pikemaster2 <- Pikemaster %>%
  filter(is.na(d13C_muscle) != TRUE & is.na(d13C_scale) != TRUE)%>%
  transmute(Fish_ID, TL_mm, Sample, Age, Cohort, Weight, Sex, Area, Capt_date, d13C_muscle, d15N_muscle, d34S_muscle, d13C_scale,
            d15N_scale, d34S_scale)%>%
  distinct()

#plot
t.test(Pikemaster2$d13C_muscle, Pikemaster2$d13C_scale, paired = TRUE)
summary(lm(d13C_muscle~d13C_scale, data = Pikemaster2))

ggplot(Pikemaster2, aes(d13C_scale, d13C_muscle))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()

png(filename = "Figures/Pike-iso-conversion_d13C.png", width = 5000, height = 2500, res = 600)
plot(d13C_muscle~d13C_scale, data = Pikemaster2)
abline(-5.46, 0.84)
dev.off()

#Correction factor for scale d13C: -3.2

t.test(Pikemaster2$d15N_muscle, Pikemaster2$d15N_scale, paired = TRUE)
summary(lm(d15N_muscle~d15N_scale, data = Pikemaster2))

ggplot(Pikemaster2, aes(d15N_scale, d15N_muscle))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()


png(filename = "Figures/Pike-iso-conversion_d15N.png", width = 5000, height = 2500, res = 600)
plot(d15N_muscle~d15N_scale, data = Pikemaster2)
abline(5.15, 0.65)
dev.off()

#Correction factor for scale d15N: -0.5

t.test(Pikemaster2$d34S_muscle, Pikemaster2$d34S_scale, paired = TRUE)
#Not different, so no correction needed

Pikemaster3 <- Pikemaster %>%
  mutate(d13C_scale = d13C_scale-3.2,
         d15N_scale = d15N_scale-0.5,
         d34S_scale = d34S_scale)

#fwrite(Pikemaster3, "Data/Pike/Pikemaster.csv")
```

```{r prey fish scale isotope data, include=FALSE, eval=FALSE}
rm(list = ls())

Isoall <- fread("Data/Pike/2024-06-21_NCS_TRittweg_Results.CSV")
Prey_recent <- fread("Data/Prey/Preyfish_SI_clean_average_lipid-corrected.csv")
Prey_historic <- fread("Data/Prey/Preyfish_samples_historic.CSV")

Prey_historic2 <- Prey_historic %>%
  transmute(Fish_ID = Number,
            Species = paste0(Species, "_historic"), 
            SL_mm = `Length [mm]`,
            weight_g = `Weight [g]`,
            height_mm = `Heigth [mm]`,
            sample_type = `Sample type`,
            area = Waterbody,
            capt_date = Date,
            Long, Lat)

Isoscales <- Isoall %>%
  filter(Identifier_1 == "scale" & !startsWith(Identifier_2, "BH"))%>%
  reframe(Fish_ID = case_when(startsWith(Identifier_2, "BH") ~ paste0(substr(Identifier_2, 1,2), "-", substr(Identifier_2, 3,7)),
                             TRUE ~ Identifier_2),
            d13C = as.numeric(`d13C/12C_Calculated`),
            d15N = as.numeric(`d15N/14N_Calculated`),
            d34S = as.numeric(`d34S/32S_Calculated`),
            CN_ratio = as.numeric(Cperc)/as.numeric(Nperc))

#Join isotope data and correct for scale offset
Prey_historic3 <- Prey_historic2 %>%
  left_join(Isoscales, by = "Fish_ID")%>%
  group_by(Fish_ID) %>%
  reframe(ID = Fish_ID,
          Species, SL_mm, weight_g, height_mm, sample_type, area, capt_date, Long, Lat,
          d13C = mean(d13C)-3.2,
          d15N = mean(d15N)-0.5,
          d34S = mean(d34S),
          CN_ratio,
          comment1 = NA,
          comment2 = NA,
          SL_size_class = NA) %>%
  select(!Fish_ID) %>%
  distinct()

Prey_all <- rbind(Prey_recent, Prey_historic3)

fwrite(Prey_all, "Data/Prey/Prey-data-all.csv")
```

```{r scale isotopes plot, include=FALSE, eval=FALSE}
rm(list = ls())

Pike <- fread("Data/Pike/Pikemaster.csv")
Prey <- fread("Data/Prey/Prey-data-all.csv")

Pike_recent <- Pike %>%
  filter(Sample == "Recent" &
           !Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek", "Badendycksgraben", "Barthe/Peene"))%>%
  transmute(Fish_ID,
            Length = TL_mm,
            Sample,
            Capt_date, Weight, 
            Sample_type = "Muscle",
            Area,
            d15N = d15N_muscle,
            d13C = d13C_muscle,
            d34S = d34S_muscle) %>%
  drop_na(d34S)%>%
  distinct()

#Historic pike scale SI data, correct d13C - 3.2 and d15N -0.5

Pike_historic <- Pike %>%
  filter(Sample == "Historic" &
           !Area %in% c("Sehrowbach", "Barthe", "Peene", "KWB", "Duwenbeek", "Beek", "Badendycksgraben", "Barthe/Peene"))%>%
  transmute(Fish_ID,
            Length = TL_mm,
            Sample,
            Capt_date, Weight, 
            Sample_type = "Muscle",
            Area,
            d15N = d15N_scale,
            d13C = d13C_scale,
            d34S = d34S_scale) %>%
  drop_na(d34S) %>%
  distinct()

Prey2 <- Prey %>%
  transmute(Fish_ID = ID, 
            Species, 
            Capt_date = as.Date(lubridate::parse_date_time(gsub("\ .", "-", capt_date), orders = "dmy")), 
            Length = SL_mm,
            Weight = weight_g,
            Sample_type = sample_type,
            Area = area,
            d15N, d13C, d34S) %>%
  filter(Species %in% c("C.harengus", "C. harengus_historic", "R.rutilus", "R. rutilus_historic",
                                  "P.fluviatilis", "P.fluviatilis_historic", "N.melanostomus", "P.flesus",
                                  "Z.viviparus", "S.lucioperca", "G.cernua"))

Pike <- rbind(Pike_recent, Pike_historic)


length_by_sp<-aggregate(cbind(d15N, d13C, d34S)~Species, data=Prey2, FUN=length)
length_by_sp

m_by_sp<-aggregate(cbind(d15N, d13C, d34S)~Species, data=Prey2, FUN=mean)

sd_by_sp<-aggregate(cbind(d15N, d13C, d34S)~Species, data=Prey2, FUN=sd)

descriptive<-cbind(m_by_sp, sd_by_sp)
descriptive<-descriptive[-5]
colnames(descriptive)<-c("Sp", "d15N", "d13C", "d34S", "sdd15N", "sdd13C", "sdd34S")
descriptive

descriptiveprey <- descriptive%>%
  drop_na()

descriptiveprey$Sp <- as.factor(descriptiveprey$Sp)

Pike$Species <- as.factor(Pike$Species)

###Get rid of all the useless species!!! Only the ones with relevant stomach percentage! rm(list = ls())

descriptiveprey$Sp <- fct_relevel(descriptiveprey$Sp, "C.harengus", "C. harengus_historic", "R.rutilus", "R. rutilus_historic",
                                  "P.fluviatilis", "P.fluviatilis_historic", "N.melanostomus", "P.flesus",
                                  "Z.viviparus", "S.lucioperca", "G.cernua")

#Biplot by species
colorBlindBlack8  <- c("#00BFB2", "cyan", "#D95F02", "darkorange", "brown4", "red", "#A6761D", "#004643",
                       "#7570B3", "#E6AB02", "darkred", "darkgrey" ,"#1B9E77","darkgreen")


CN <- ggplot()+  
  stat_density_2d(data = Pike, aes(x = d13C, y = d15N, fill = Sample), 
                  alpha = 0.5, geom = "polygon", linewidth = .1)+ 
  geom_errorbar(data=descriptiveprey, aes(x=d13C, y=d15N, ymin = d15N-sdd15N,ymax = d15N+sdd15N, col=Sp),
                        width=.5, size=.5, show.legend = FALSE) +
  geom_errorbarh(data=descriptiveprey, aes(x=d13C, y=d15N, xmin = d13C+sdd13C,xmax = d13C-sdd13C, col=Sp),
                 height=.5, size=.5, show.legend = FALSE)+
  geom_line(data = descriptiveprey, aes(d13C, d15N, col = Sp), linewidth = 0.8, alpha = 0)+
  labs(fill = "Pike sample", col = "Prey species")+
  theme_bw()+xlab(delta^"13"~"C(\u2030)")+ylab(delta^"15"~"N(\u2030)")+
  scale_colour_manual(values=c("C.harengus" = "#1B9E77", "C. harengus_historic" = "#004643", "R.rutilus" = "#66A61E", 
                              "R. rutilus_historic" = "darkgreen", "P.fluviatilis" = "#D95F02", "P.fluviatilis_historic" = "darkred",
                              "Z.viviparus" = "#7570B3", "P.flesus" = "#E7298A", "G.cernua" = "#E6AB02", "N.melanostomus" = "cyan", 
                              "S.lucioperca" = "#A6761D"),
                      labels = c("C.harengus" = "C. harengus", "C. harengus_historic" = "Historic C. harengus", "R.rutilus" = "R. rutilus", 
                              "R. rutilus_historic" = "Historic R. rutilus", "P.fluviatilis" = "P. fluviatilis", 
                              "P.fluviatilis_historic" = "Historic P. fluviatilis", "Z.viviparus" = "Z. viviparus", 
                              "P.flesus" = "P. flesus", "G.cernua" = "G. cernua", "N.melanostomus" = "N. melanostomus", 
                              "S.lucioperca" = "S. luciuperca"))+
  scale_fill_manual(breaks = c("Historic", "Recent"), 
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic pike", "Recent pike"))+
  theme(text = element_text(size = 10, color = "black"),
        legend.position="bottom",
        legend.text = element_text(color = "black", size=5, face="italic"),
        legend.key.size = unit(.2, 'cm'),
        strip.background = element_rect(colour="black", fill="white"),
        legend.key = element_blank())+
  guides(colour = guide_legend(override.aes = list(fill = NA, linewidth = 0.8)))

CS <- ggplot()+  
  stat_density_2d(data = Pike, aes(x = d13C, y = d34S, fill = Sample), 
                  alpha = 0.5, geom = "polygon", linewidth = .1)+ 
  geom_errorbar(data=descriptiveprey, aes(x=d13C, y=d34S, ymin = d34S-sdd34S,ymax = d34S+sdd34S, col=Sp),
                        width=.5, size=.5, show.legend = FALSE) +
  geom_errorbarh(data=descriptiveprey, aes(x=d13C, y=d34S, xmin = d13C+sdd13C,xmax = d13C-sdd13C, col=Sp),
                 height=.5, size=.5, show.legend = FALSE)+
  geom_line(data = descriptiveprey, aes(d13C, d34S, col = Sp), linewidth = 0.8, alpha = 0)+
  labs(fill = "Pike sample", col = "Prey species")+
  theme_bw()+xlab(delta^"13"~"C(\u2030)")+ylab(delta^"34"~"S(\u2030)")+
  scale_colour_manual(values=c("C.harengus" = "#1B9E77", "C. harengus_historic" = "#004643", "R.rutilus" = "#66A61E", 
                              "R. rutilus_historic" = "darkgreen", "P.fluviatilis" = "#D95F02", "P.fluviatilis_historic" = "darkred",
                              "Z.viviparus" = "#7570B3", "P.flesus" = "#E7298A", "G.cernua" = "#E6AB02", "N.melanostomus" = "cyan", 
                              "S.lucioperca" = "#A6761D"),
                      labels = c("C.harengus" = "C. harengus", "C. harengus_historic" = "Historic C. harengus", "R.rutilus" = "R. rutilus", 
                              "R. rutilus_historic" = "Historic R. rutilus", "P.fluviatilis" = "P. fluviatilis", 
                              "P.fluviatilis_historic" = "Historic P. fluviatilis", "Z.viviparus" = "Z. viviparus", 
                              "P.flesus" = "P. flesus", "G.cernua" = "G. cernua", "N.melanostomus" = "N. melanostomus", 
                              "S.lucioperca" = "S. luciuperca"))+
  scale_fill_manual(breaks = c("Historic", "Recent"), 
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic pike", "Recent pike"))+
  theme(text = element_text(size = 10, color = "black"),
        legend.position="none",
        legend.text = element_text(color = "black", size=5, face="italic"),
        legend.key.size = unit(.5, 'cm'),
        strip.background = element_rect(colour="black", fill="white"),
        legend.key = element_blank())+
  guides(colour = guide_legend(override.aes = list(fill = NA, linewidth = 0.8)))

NS <- ggplot()+  
  stat_density_2d(data = Pike, aes(x = d15N, y = d34S, fill = Sample), 
                  alpha = 0.5, geom = "polygon", linewidth = .1)+ 
  geom_errorbar(data=descriptiveprey, aes(x=d15N, y=d34S, ymin = d34S-sdd34S,ymax = d34S+sdd34S, col=Sp),
                        width=.5, size=.5, show.legend = FALSE) +
  geom_errorbarh(data=descriptiveprey, aes(x=d15N, y=d34S, xmin = d15N+sdd15N,xmax = d15N-sdd15N, col=Sp),
                 height=.5, size=.5, show.legend = FALSE)+
  geom_line(data = descriptiveprey, aes(d15N, d34S, col = Sp), linewidth = 0.8, alpha = 0)+
  labs(fill = "Pike sample", col = "Prey species")+
  theme_bw()+xlab(delta^"15"~"N(\u2030)")+ylab(delta^"34"~"S(\u2030)")+
  scale_colour_manual(values=c("C.harengus" = "#1B9E77", "C. harengus_historic" = "#004643", "R.rutilus" = "#66A61E", 
                              "R. rutilus_historic" = "darkgreen", "P.fluviatilis" = "#D95F02", "P.fluviatilis_historic" = "darkred",
                              "Z.viviparus" = "#7570B3", "P.flesus" = "#E7298A", "G.cernua" = "#E6AB02", "N.melanostomus" = "cyan", 
                              "S.lucioperca" = "#A6761D"),
                      labels = c("C.harengus" = "C. harengus", "C. harengus_historic" = "Historic C. harengus", "R.rutilus" = "R. rutilus", 
                              "R. rutilus_historic" = "Historic R. rutilus", "P.fluviatilis" = "P. fluviatilis", 
                              "P.fluviatilis_historic" = "Historic P. fluviatilis", "Z.viviparus" = "Z. viviparus", 
                              "P.flesus" = "P. flesus", "G.cernua" = "G. cernua", "N.melanostomus" = "N. melanostomus", 
                              "S.lucioperca" = "S. luciuperca"))+
  scale_fill_manual(breaks = c("Historic", "Recent"), 
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic pike", "Recent pike"))+
  theme(text = element_text(size = 10, color = "black"),
        legend.position="none",
        legend.text = element_text(color = "black", size=5, face="italic"),
        legend.key.size = unit(.5, 'cm'),
        strip.background = element_rect(colour="black", fill="white"),
        legend.key = element_blank())+
  guides(colour = guide_legend(override.aes = list(fill = NA, linewidth = 0.8)))


Ecopike <- ggarrange(CN, CS, NS, ncol = 3, nrow = 1, common.legend = T)

ggsave("Figures/Biplot-historic-vs-Recent.png", Ecopike, width = 16, height = 6, units = "cm", dpi = 600, bg = "white")
saveRDS(Ecopike, "Data/Pike/Biplot-figure.rds")
```

```{r isotope modelling, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
Prey_all <- fread("Data/Prey/Prey-data-all.csv")

Pikedata <- Pikemaster%>%
  transmute(Fish_ID, 
            TL_cm = TL_mm/10, 
            Sample, Area, Genotype, d13C_muscle, d15N_muscle, d34S_muscle, d13C_scale, d15N_scale, d34S_scale) %>%
  mutate(d13C = case_when(is.na(d13C_muscle) ~ d13C_scale,
                          TRUE ~ d13C_muscle),
         d15N = case_when(is.na(d15N_muscle) ~ d15N_scale,
                          TRUE ~ d15N_muscle),
         d34S = case_when(is.na(d34S_muscle) ~ d34S_scale,
                          TRUE ~ d34S_muscle))%>%
  drop_na(d34S) %>%
  distinct()

Pikedata2 <- Pikedata %>% filter(is.na(Genotype) == FALSE)

#GAM or Linear?

fit_lin_S <- brm(d34S ~ TL_cm + Genotype + Sample + (1|Area),
  data = Pikedata,
  family = gaussian(),
  prior = c(prior(normal(0, 5), class = "b"),          # fixed effects
            prior(student_t(3, 0, 5), class = "Intercept"),
            prior(exponential(1), class = "sd"),       # random effect SDs
            prior(exponential(1), class = "sigma")),     # residual SD
  chains = 4, iter = 4000, warmup = 2000)

fit_lin_C <- update(fit_lin, formula. = d13C ~ TL_cm + Genotype + Sample + (1|Area), newdata = Pikedata)
fit_lin_N <- update(fit_lin, formula. = d15N ~ TL_cm + Genotype + Sample + (1|Area), newdata = Pikedata)

fit_gam_S <- brm(d34S ~ s(TL_cm, k = 10) + Genotype + Sample + (1|Area),
  data = Pikedata,
  family = gaussian(),
  prior = c(prior(normal(0, 5), class = "b"),
            prior(student_t(3, 0, 5), class = "Intercept"),
            prior(exponential(1), class = "sd"),
            prior(exponential(1), class = "sigma"),
            prior(exponential(1), class = "sds")),       # smooth SD/penalty scale
  chains = 4, iter = 4000, warmup = 2000)

fit_gam_C <- update(fit_gam_S, formula. = d13C ~ s(TL_cm, k = 10) + Genotype + Sample + (1|Area), newdata = Pikedata)
fit_gam_N <- update(fit_gam_S, formula. = d15N ~ s(TL_cm, k = 10) + Genotype + Sample + (1|Area), newdata = Pikedata)

loo_linS <- loo(fit_lin)
loo_linC <- loo(fit_lin_C)
loo_linN <- loo(fit_lin_N)
loo_gamS <- loo(fit_gam_S)
loo_gamC <- loo(fit_gam_C)
loo_gamN <- loo(fit_gam_N)

loo_compare(loo_linS, loo_gamS)
#GAM significantly better, dlooic = 8.6
loo_compare(loo_linC, loo_gamC)
#GAM significantly better, dlooic = 14.0
loo_compare(loo_linN, loo_gamN)
#GAM not significantly better, dlooic = 0.8 (worse)

fit_gamS_int <- brm(d34S ~ s(TL_cm, by = Sample, k = 10) + Sample + Genotype + (1|Area),
  data = Pikedata,
  family = gaussian(),
  prior = c(prior(normal(0, 5), class = "b"),
            prior(student_t(3, 0, 5), class = "Intercept"),
            prior(exponential(1), class = "sd"),
            prior(exponential(1), class = "sigma"),
            prior(exponential(1), class = "sds")),       # smooth SD/penalty scale
  chains = 4, iter = 4000, warmup = 2000)

fit_gamC_int <- update(fit_gamS_int, formula. = d13C ~ s(TL_cm, by = Sample, k = 10) + Sample + Genotype + (1|Area), newdata = Pikedata)
fit_linN_int <- update(fit_lin_N, formula. = d15N ~ TL_cm * Sample + Genotype + Sample + (1|Area), newdata = Pikedata)

loo_intS <- loo(fit_gamS_int)
loo_intC <- loo(fit_gamC_int)
loo_intN <- loo(fit_linN_int)

loo_compare(loo_gamS, loo_intS)
#Interaction highly significant, dlooic = 10.6
loo_compare(loo_gamC, loo_intC)
#Interaction not significant --> continue without, dlooic = 1.0 (worse)
loo_compare(loo_linN, loo_intN)
#Interaction weakly significant, dlooic = 3.0

fit_noSampS <- brm(d34S ~ s(TL_cm, by = Sample, k = 10) + Genotype + (1|Area),
  data = Pikedata,
  family = gaussian(),
  prior = c(prior(normal(0, 5), class = "b"),
            prior(student_t(3, 0, 5), class = "Intercept"),
            prior(exponential(1), class = "sd"),
            prior(exponential(1), class = "sigma"),
            prior(exponential(1), class = "sds")),       # smooth SD/penalty scale
  chains = 4, iter = 4000, warmup = 2000)

fit_noSampC <- update(fit_noSampS, formula. = d13C ~ s(TL_cm, by = Sample, k = 10) + Genotype + (1|Area), newdata = Pikedata)
fit_noSampN <- update(fit_linN_int, formula. = d15N ~ TL_cm * Sample + Genotype + (1|Area), newdata = Pikedata)

loo_noSampS <- loo(fit_noSampS)
loo_noSampC <- loo(fit_noSampC)
loo_noSampN <- loo(fit_noSampN)

loo_compare(loo_noSampS, loo_intS)
#Sample is not significant dloo = 1.0
loo_compare(loo_noSampC, loo_gamC)
#sample is highly significant dloo = 33.6
loo_compare(loo_noSampN, loo_intN)
#sample is not significant dloo = 0.2

fit_noGenS <- update(fit_noSampS, formula. = d34S ~ s(TL_cm, by = Sample, k = 10) + (1|Area), newdata = Pikedata2)
fit_noGenC <- update(fit_gam_C, formula. = d13C ~ s(TL_cm, k = 10) + Sample + (1|Area), newdata = Pikedata2)
fit_noGenN <- update(fit_linN_int, formula. = d15N ~ TL_cm * Sample + Sample + (1|Area), newdata = Pikedata2)

loo_noGenS <- loo(fit_noGenS)
loo_noGenC <- loo(fit_noGenC)
loo_noGenN <- loo(fit_noGenN)

loo_compare(loo_noGenS, loo_noSampS)
#Genotype not significant, improve dlooic by 1.0
loo_compare(loo_noGenC, loo_gamC)
#Genotype not significant, improve dlooic by 0.5
loo_compare(loo_noGenN, loo_noSampN)
#Genotype not significant, improve dlooic by 0.7

d34S_final <- update(fit_noSampS, formula. = d34S ~ s(TL_cm, by = Sample, k = 10) + (1|Area), newdata = Pikedata)
d13C_final <- update(fit_gam_C, formula. = d13C ~ s(TL_cm, k = 10) + Sample + (1|Area), newdata = Pikedata)
d15N_final <- update(fit_linN_int, formula. = d15N ~ TL_cm * Sample + (1|Area), newdata = Pikedata)
```

```{r isotope figures, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
Prey_all <- fread("Data/Prey/Prey-data-all.csv")

Pikedata <- Pikemaster%>%
  transmute(Fish_ID, 
            TL_cm = TL_mm/10, 
            Sample, Area, Genotype, d13C_muscle, d15N_muscle, d34S_muscle, d13C_scale, d15N_scale, d34S_scale) %>%
  mutate(d13C = case_when(is.na(d13C_muscle) ~ d13C_scale,
                          TRUE ~ d13C_muscle),
         d15N = case_when(is.na(d15N_muscle) ~ d15N_scale,
                          TRUE ~ d15N_muscle),
         d34S = case_when(is.na(d34S_muscle) ~ d34S_scale,
                          TRUE ~ d34S_muscle))%>%
  drop_na(d34S) %>%
  distinct()

plot_theme <- theme(panel.grid.major = element_line(linewidth = .3, colour = "lightgrey"),
        legend.position = "none",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(linewidth = 0.5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.y = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, colour = "black"),
        legend.text = element_text(size = 10, colour = "black"),
        legend.title = element_text(size = 10, colour = "black"),
        legend.key.size = unit(1,"line"))

Carb <- ggplot(Pikedata, aes(TL_cm, d13C, colour = Sample))+
  geom_point(size = .5)+
  geom_smooth(method = "gam")+
  scale_color_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 130)", "Recent (N = 519)"))+
  labs(x = "Total length (cm)", y=expression(delta^"13"~"C(\u2030)"), fill="Sample")+
  theme_classic()+
  plot_theme

Nitro <- ggplot(Pikedata, aes(TL_cm, d15N, colour = Sample))+
  geom_point(size = .5)+
  geom_smooth(method = "lm")+
  scale_color_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 130)", "Recent (N = 519)"))+
  labs(x = "Total length (cm)", y=expression(delta^"15"~"N(\u2030)"), fill="Sample")+
  theme_classic()+
  plot_theme

Sulf <- ggplot(Pikedata, aes(TL_cm, d34S, colour = Sample))+
  geom_point(size = .5)+
  geom_smooth(method = "gam")+
  scale_color_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 130)", "Recent (N = 519)"))+
  labs(x = "Total length (cm)", y=expression(delta^"34"~"S(\u2030)"), fill="Sample")+
  theme_classic()+
  plot_theme

Isos <- ggarrange(Carb, Nitro, Sulf, nrow = 1, common.legend = TRUE, legend = "bottom")
Isos1 <- annotate_figure(Isos, top = text_grob("Body-size specific pike isotope values", size = 15, just = 0.5))

Biplot <- readRDS("Data/Pike/Biplot-figure.rds")
Biplot1 <- annotate_figure(Biplot, top = text_grob("Isotope biplots for pike and prey fish", size = 15, just = 0.5))

Isoall <- ggarrange(Biplot1, Isos1, ncol = 1)
ggsave("Figures/Isotopes_historic-vs-Recent.png", Isoall, width = 16, height = 16, units = "cm", dpi = 600, bg = "white")
```

```{r isotope figures genotypes, include=FALSE, eval=FALSE}
rm(list = ls())

Pikemaster <- fread("Data/Pike/Pikemaster.csv")
Prey_all <- fread("Data/Prey/Prey-data-all.csv")

Pikedata <- Pikemaster%>%
  filter(Genotype %in% c(1, 2, 3, 4))%>%
  transmute(Fish_ID, 
            TL_cm = TL_mm/10, 
            Sample, Area, Genotype, d13C_muscle, d15N_muscle, d34S_muscle, d13C_scale, d15N_scale, d34S_scale) %>%
  mutate(d13C = case_when(is.na(d13C_muscle) ~ d13C_scale,
                          TRUE ~ d13C_muscle),
         d15N = case_when(is.na(d15N_muscle) ~ d15N_scale,
                          TRUE ~ d15N_muscle),
         d34S = case_when(is.na(d34S_muscle) ~ d34S_scale,
                          TRUE ~ d34S_muscle))%>%
  drop_na(d34S) %>%
  distinct()

plot_theme <- theme(panel.grid.major = element_line(linewidth = .3, colour = "lightgrey"),
        legend.position = "none",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(linewidth = 0.5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.y = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, colour = "black"),
        legend.text = element_text(size = 10, colour = "black"),
        legend.title = element_text(size = 10, colour = "black"),
        legend.key.size = unit(1,"line"))

geno_labels <- c("1" = "Genotype 1", "2" = "Genotype 2", "3" = "Genotype 3", "4" = "Genotype 4")

Carb <- ggplot(Pikedata, aes(TL_cm, d13C, colour = Sample))+
  geom_point(size = .3)+
  geom_smooth(method = "gam", linewidth = .3)+
  scale_color_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 130)", "Recent (N = 519)"))+
  facet_wrap(~Genotype, nrow = 1, labeller = labeller(Genotype = geno_labels))+
  labs(x = "Total length (cm)", y=expression(delta^"13"~"C(\u2030)"), fill="Sample")+
  theme_classic()+
  plot_theme

Nitro <- ggplot(Pikedata, aes(TL_cm, d15N, colour = Sample))+
  geom_point(size = .3)+
  geom_smooth(method = "lm", linewidth = 0.3)+
  scale_color_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 130)", "Recent (N = 519)"))+
  facet_wrap(~Genotype, nrow = 1, labeller = labeller(Genotype = geno_labels))+
  labs(x = "Total length (cm)", y=expression(delta^"15"~"N(\u2030)"), fill="Sample")+
  theme_classic()+
  plot_theme

Sulf <- ggplot(Pikedata, aes(TL_cm, d34S, colour = Sample))+
  geom_point(size = .3)+
  geom_smooth(method = "gam", linewidth = 0.3)+
  scale_color_manual(breaks = c("Historic","Recent"),
                    values = c("#00BFB2","#C5D86D"),
                    labels = c("Historic (N = 130)", "Recent (N = 519)"))+
  facet_wrap(~Genotype, nrow = 1, labeller = labeller(Genotype = geno_labels))+
  labs(x = "Total length (cm)", y=expression(delta^"34"~"S(\u2030)"), fill="Sample")+
  theme_classic()+
  plot_theme

Isos <- ggarrange(Carb, Nitro, Sulf, ncol = 1, common.legend = TRUE, legend = "bottom")
Isos1 <- annotate_figure(Isos, top = text_grob("Body-size specific pike isotope values", size = 15, just = 0.5))

ggsave("Figures/Isotopes_historic-vs-Recent-genotypes.png", Isos1, width = 16, height = 12, units = "cm", dpi = 600, bg = "white")
```


# Population model

```{r model parameters, include=FALSE, eval=FALSE}

# Parameters - for Age Pike Model
# Created by: Elias Ehrlich


# Parameters

Bodden_area = 125200 #according to Rob van Gemerts' data in handover folder #126560 #170000 # [ha] 

a_max = 15                # Maximum age [years]
#M_min = 0.15              # Minimum adult natural mortality rate [year^-1]
M_min = 0.25              # Minimum adult natural mortality rate [year^-1]
theta = 0.5               # Lorenzen size-dependent mortality power (0-1.2)
#theta = 1.0               # Lorenzen size-dependent mortality power (0-1.2)

alpha_w = 0.0045          # Length-weight scaling constant
beta_w = 3.107            # Allometric parameter

l_mat = 375               # Length-at-maturation [mm]
alpha_f = 9.8             # Fecundity-weight scaling constant
beta_f = 1.12             # Power parameter relating fecundity to weight

R0 = 1.0*10^6             # Average total age-1 recruitment in the unfished stock []
SexRatioRecruits = 0.5    # females/(females+males)
CR = 6.1                  # Compensation ratio (paper: Goodyear 1980) []

#lmin_c = 375              # Minimum length at which vulnverable to capture [mm] 
lmin_c = 400              # Minimum length at which vulnverable to capture [mm] 
lmax_c = 1500             # Maximum length at which vulnerable to capture [mm]
#lmin_r = 375              # Minimum length at which vulnverable to capture [mm] 
lmin_r = 500              # Minimum length vulnerable to harvest [mm]
lmax_r = 1500             # Maximum length vulnerable to harvest [mm]

l_troph = 1000            # Minimum total length of a trophy fish [mm]

#F_mort = 0.1              # Instantaneous fishing mortality on individuals with selectivity of 1 [year^-1] (current situation)
F_mort = 0.2              # Instantaneous fishing mortality on individuals with selectivity of 1 [year^-1] (current situation)
d = 0.078                 # Discard mortality []; e.g. f_h=0.1 --> 10 % of released fish die 

# Growth parameters based on 3 different aging methods using scales, otoliths or the corroborated age, respectively (=3 values for each parameter)
measure_L8 = c(1230, 1020, 818,0)            # Measured mean asymptotic length L_8 (van Bertalanffy growth function VBGF) [mm] 
measure_k = c(0.2, 0.296, 0.388)              # Measured VBGF growth coefficient k [year^-1] for scale, otolith and corroborated age, respectively
measure_t0 = c(-0.349, -0.496, -0.297)             # Measured theoretical age at length of 0 t_0 [years] for scale, otolith and corroborated age, respectively
sd_L8 = c(198, 85.5, 109.5)                  # Standard deviation of L_8 [mm] of measurement for scale, otolith and corroborated age, respectively
sd_k = c(0.05, 0.055, 0.08)                  # Standard deviation of k [year^-1] of measurement for scale, otolith and corroborated age, respectively
sd_t0 = c(0.15, 0.15, 0.15)                  # Standard deviation of t_0 [years] of measurement for scale, otolith and corroborated age, respectively

CI_5_L8 = c(1160.0, 993.0, 784.0)            # 5 % confidence level for L_8 estimates
CI_95_L8 = c(1310.0, 1050.0, 857.0)         # 95 % confidence level for L_8 estimates
CI_5_k = c(0.177, 0.271, 0.337)                 # 5 % confidence level for k estimates
CI_95_k = c(0.226, 0.323, 0.451)                # 95 % confidence level for k estimates
CI_5_t0 = c(-0.489, -0.636, -0.441)             # 5 % confidence level for t_0 estimatees
CI_95_t0 = c(-0.21, -0.347, -0.147)            # 95 % confidence level for t_0 estimates

cv = 0.13                                   # Coefficient of variation in VBGF among individuals

# Random seed number for reproducibility of results
RandomSeedNr = 126
```

```{r pike age model & figure 7, include=FALSE, eval=FALSE}

# Pike model: Effect of different ageing methods on fishery reference points and optimal minimum length limit  
# Code author: Elias Ehrlch           


setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # set working directory to source file (for using RStudio)


# Load Packages and functions

library(matrixStats)
library(reshape2)
library(ggplot2)
library(patchwork)


# Setting

SAVE = 0                  # Set to 1 to save png plot and to 0 if not


# Loading Data

#source("Data/AgePikeModel_Parameters.R") # Import parameters

path = "Data/SimData/FishRefPoints/"
F_mort_vec = readRDS(file=paste0(path, "F_mort.rds"))               # Scenarios of instantaneous fishing mortalities
N_vec_rep = readRDS(file=paste0(path, "N_F_mort.rds"))              # Temporal average total stock size
HarvN_vec_rep = readRDS(file=paste0(path, "HarvN_F_mort.rds"))      # Temporal average harvestable stock size
VulnN_vec_rep = readRDS(file=paste0(path, "VulnN_F_mort.rds"))      # Temporal average stock size vulnerable to catch
TrophyN_vec_rep = readRDS(file=paste0(path, "TrophyN_F_mort.rds"))  # Temporal average trophy stock size
AmountTrophy_vec_rep = readRDS(file=paste0(path, "AmountTrophy_F_mort.rds"))  # Temporal average amount of trophy fish in population
B_vec_rep = readRDS(file=paste0(path, "B_F_mort.rds"))              # Temporal average total biomass
Y_vec_rep = readRDS(file=paste0(path, "Y_F_mort.rds"))              # Temporal average yield
YN_vec_rep = readRDS(file=paste0(path, "YN_F_mort.rds"))            # Temporal average yield

n_meth = dim(N_vec_rep) [3]                 # Number of different aging methods
n_rep = dim(N_vec_rep) [2]                  # Number of random samples of growth parameters per aging method
n = dim(N_vec_rep) [1]                      # Number of scenarios of F


# Calculating fisheries reference points

# Fishery reference points for each random sample of growth parameters for the n_meth=3 aging methods
MSY_rep = matrix(NA, n_rep, n_meth)
F_MSY_rep = matrix(NA, n_rep, n_meth)
B_MSY_rep = matrix(NA, n_rep, n_meth)
N_MSY_rep = matrix(NA, n_rep, n_meth)
HarvN_MSY_rep = matrix(NA, n_rep, n_meth)
VulnN_MSY_rep = matrix(NA, n_rep, n_meth)
TrophyN_MSY_rep = matrix(NA, n_rep, n_meth)

YNmax_rep = matrix(NA, n_rep, n_meth) 

for (h in 1:n_meth){
  MSY_rep[,h] = apply(Y_vec_rep[,,h], 2, max)                 # MSY (=highest temporal mean yield over all scenarios) for each growth parameter sample
  Index_max = apply(Y_vec_rep[,,h], 2, which.max)             # Index of MSY in output metrix Y_vec_rep[,,h] for each growth parameter sample
  F_MSY_rep[,h] = F_mort_vec[Index_max]                       # F_MSY for each growth parameter sample
  for (j in 1:n_rep){
    B_MSY_rep[j,h] = B_vec_rep[Index_max[j],j,h]              # B_MSY for each growth parameter sample
    N_MSY_rep[j,h] = N_vec_rep[Index_max[j],j,h]              # N_MSY for each growth parameter sample
    HarvN_MSY_rep[j,h] = HarvN_vec_rep[Index_max[j],j,h]  
    VulnN_MSY_rep[j,h] = VulnN_vec_rep[Index_max[j],j,h]  
    TrophyN_MSY_rep[j,h] = TrophyN_vec_rep[Index_max[j],j,h]
  }
  YNmax_rep[,h] = apply(YN_vec_rep[,,h], 2, max)              # Maximum number of harvested fish for each growth parameter sample
}


# Box plots for fishery reference points

F_MSY_data = data.frame(F_MSY_rep)
MSY_data = data.frame(MSY_rep)
B_MSY_data = data.frame(B_MSY_rep)
Methods = c("Historic", "Recent", "Freshwater")
colnames(F_MSY_data) = Methods
colnames(MSY_data) = Methods
colnames(B_MSY_data) = Methods

FishRefPoints = data.frame(matrix(NA, n_rep*n_meth, 4))
colnames(FishRefPoints) = c("F_MSY", "MSY", "B_MSY", "Method")
FishRefPoints$F_MSY = melt(F_MSY_data)$value
FishRefPoints$MSY = melt(MSY_data)$value
FishRefPoints$B_MSY = melt(B_MSY_data)$value
FishRefPoints$Method = melt(F_MSY_data)$variable

Col_data = c("#E69F00", "#56B4E9", "#999999")
options(scipen=5)                             # Avoiding notation of numbers as a power of ten on the axes (i.e. no 'e-5') 

p1 <- ggplot(FishRefPoints, aes(x=Method, y=F_MSY, fill=Method)) +
  geom_boxplot(outlier.shape = NA) + #--> outliers not plotted
  xlab("Aging method") +
  ylab(expression(""~ F[MSY] ~" ["~ year^{-1} ~"]")) +
  scale_fill_manual(values=Col_data) +
  theme_bw() +
  coord_cartesian(ylim = c(0.17, 0.28)) +
  scale_y_continuous(breaks=seq(0.18, 0.28, 0.02)) +
  theme(legend.position = "none")
p2 <- ggplot(FishRefPoints, aes(x=Method, y=MSY*1e3/Bodden_area, fill=Method)) +
  geom_boxplot(outlier.shape = NA) +
  xlab("Aging method") +
  ylab(expression("MSY [kg "~ ha^-1 ~ year^{-1} ~"]")) +
  scale_fill_manual(values=Col_data) +
  coord_cartesian(ylim = c(0, 8)) +
  scale_y_continuous(breaks=seq(0, 10, 2)) +
  theme_bw() +
  theme(legend.position = "none")
p3 <- ggplot(FishRefPoints, aes(x=Method, y=B_MSY*1e3/Bodden_area, fill=Method)) +
  geom_boxplot(outlier.shape = NA) +
  xlab("Aging method") +
  ylab(expression(""~ B[MSY] ~" [kg" ~ ha^-1 ~ "]")) +
  scale_fill_manual(values=Col_data) +
  coord_cartesian(ylim = c(0, 50)) +
  theme_bw() +
  theme(legend.position = "none")


# Loading Data

path = "Data/SimData/MinSizeLim/"
lmin_r_vec = readRDS(file=paste0(path, "MinSizeLim.rds"))               # Scenarios of instantaneous fishing mortalities
N_vec_rep = readRDS(file=paste0(path, "N_MinSizeLim.rds"))              # Temporal average total stock size
HarvN_vec_rep = readRDS(file=paste0(path, "HarvN_MinSizeLim.rds"))      # Temporal average harvestable stock size
VulnN_vec_rep = readRDS(file=paste0(path, "VulnN_MinSizeLim.rds"))      # Temporal average stock size vulnerable to catch
TrophyN_vec_rep = readRDS(file=paste0(path, "TrophyN_MinSizeLim.rds"))  # Temporal average trophy stock size
B_vec_rep = readRDS(file=paste0(path, "B_MinSizeLim.rds"))              # Temporal average total biomass
Y_vec_rep = readRDS(file=paste0(path, "Y_MinSizeLim.rds"))              # Temporal average yield
YN_vec_rep = readRDS(file=paste0(path, "YN_MinSizeLim.rds"))            # Temporal average numeric yield
Utility_vec_rep = readRDS(file=paste0(path, "Utility_MinSizeLim.rds"))  # Temporal average yield

n_meth = dim(N_vec_rep) [3]                 # Number of different aging methods
n_rep = dim(N_vec_rep) [2]                  # Number of random samples of growth parameters per aging method
n = dim(N_vec_rep) [1]                      # Number of scenarios of minimum size limits

##########################################
# Identifying optimal minimum length limit
##########################################
MaxUtil_rep = matrix(NA, n_rep, n_meth)
MinLL_MaxUtil_rep = matrix(NA, n_rep, n_meth)

for (h in 1:n_meth){
  MaxUtil_rep[,h] = apply(Utility_vec_rep[,,h], 2, max)       # Maximum utility for each growth parameter sample
  Index_max = apply(Utility_vec_rep[,,h], 2, which.max)       # Index of Maximum utility in output metrix Utility_vec_rep[,,h] for each growth parameter sample
  MinLL_MaxUtil_rep[,h] = lmin_r_vec[Index_max]               # Optimal minimum length limit for each growth parameter sample
}

# Mean and sd of maximum utility and optimal minimum length limit from all growth parameter samples 
MaxUtil_mean_sd = rbind( colMeans(MaxUtil_rep), colSds(MaxUtil_rep) )
MinLL_MaxUtil_mean_sd = rbind( colMeans(MinLL_MaxUtil_rep), colSds(MinLL_MaxUtil_rep) )

#########################################
# Box plots for optimal min. length limit
#########################################
OptMinLL_data = data.frame(MinLL_MaxUtil_rep)
Methods = c("Scales", "Otoliths", "Corroborated")
colnames(OptMinLL_data) = Methods

OptSizeLim = data.frame(matrix(NA, n_rep*n_meth, 2))
colnames(OptSizeLim) = c("OptMinLL", "Method")
OptSizeLim$OptMinLL = melt(OptMinLL_data)$value
OptSizeLim$Method = melt(OptMinLL_data)$variable

p4 <- ggplot(OptSizeLim, aes(x=Method, y=OptMinLL/10, fill=Method)) +
  geom_boxplot(outlier.shape = NA) + # geom_boxplot(outlier.shape = NA) #--> outliers not plotted
  xlab("Aging method") +
  ylab(expression("Optimal min. length limit [cm]")) +
  scale_fill_manual(values=Col_data) +
  theme_bw() +
  #coord_cartesian(ylim = c(0.14, 0.24)) +
  theme(legend.position = "none")

if(SAVE){png("Figures/FishRefPoints_OptMinLL_Boxplots.png", width = 4000, height = 3400, res=600)}

(p1 + p2) /
(p3 + p4) + plot_annotation(tag_levels = "a")

if(SAVE){dev.off()}

aggregate(FishRefPoints[, 1:3], list(FishRefPoints$Method), median)
aggregate(FishRefPoints[, 1:3], list(FishRefPoints$Method), mean)
aggregate(OptSizeLim[, 1], list(OptSizeLim$Method), median)
aggregate(OptSizeLim[, 1], list(OptSizeLim$Method), mean)
```

```{r pike age model & figure 8, include=FALSE, eval=FALSE}
####################################################################################
# Pike model: Effect of different age reading methods on fishery reference points  
# Code author: Elias Ehrlch           
####################################################################################

setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # set working directory to source file (for using RStudio)

#############################
# Load Packages and functions
#############################
library(matrixStats)
library(reshape2)
library(ggplot2)
library(patchwork)

#########
# Setting
#########
SAVE = 1                  # Set to 1 to save png plot and to 0 if not

##############
# Loading Data
##############
#source("AgePikeModel_Parameters.R") # Import parameters

path = "Data/SimData/FishRefPoints/"
F_mort_vec = readRDS(file=paste0(path, "F_mort.rds"))               # Scenarios of instantaneous fishing mortalities
N_vec_rep = readRDS(file=paste0(path, "N_F_mort.rds"))              # Temporal average total stock size
HarvN_vec_rep = readRDS(file=paste0(path, "HarvN_F_mort.rds"))      # Temporal average harvestable stock size
VulnN_vec_rep = readRDS(file=paste0(path, "VulnN_F_mort.rds"))      # Temporal average stock size vulnerable to catch
TrophyN_vec_rep = readRDS(file=paste0(path, "TrophyN_F_mort.rds"))  # Temporal average trophy stock size
AmountTrophy_vec_rep = readRDS(file=paste0(path, "AmountTrophy_F_mort.rds"))  # Temporal average amount of trophy fish in population
B_vec_rep = readRDS(file=paste0(path, "B_F_mort.rds"))              # Temporal average total biomass
Y_vec_rep = readRDS(file=paste0(path, "Y_F_mort.rds"))              # Temporal average yield
YN_vec_rep = readRDS(file=paste0(path, "YN_F_mort.rds"))            # Temporal average yield

n_meth = dim(N_vec_rep) [3]                 # Number of different aging methods
n_rep = dim(N_vec_rep) [2]                  # Number of random samples of growth parameters per aging method
n = dim(N_vec_rep) [1]                      # Number of scenarios of F

########################################
# Calculating fisheries reference points
########################################
# Fishery reference points for each random sample of growth parameters for the n_meth=3 aging methods
MSY_rep = matrix(NA, n_rep, n_meth)
F_MSY_rep = matrix(NA, n_rep, n_meth)
B_MSY_rep = matrix(NA, n_rep, n_meth)
N_MSY_rep = matrix(NA, n_rep, n_meth)
HarvN_MSY_rep = matrix(NA, n_rep, n_meth)
VulnN_MSY_rep = matrix(NA, n_rep, n_meth)
TrophyN_MSY_rep = matrix(NA, n_rep, n_meth)

YNmax_rep = matrix(NA, n_rep, n_meth) 

# my.max <- function(x) ifelse( !all(is.na(x)), max(x, na.rm=T), NA) # if every (all) element in x is NA, then NA is returned, and the max otherwise

for (h in 1:n_meth){
  MSY_rep[,h] = apply(Y_vec_rep[,,h], 2, max)                 # MSY (=highest temporal mean yield over all scenarios) for each growth parameter sample
  Index_max = apply(Y_vec_rep[,,h], 2, which.max)             # Index of MSY in output metrix Y_vec_rep[,,h] for each growth parameter sample
  F_MSY_rep[,h] = F_mort_vec[Index_max]                       # F_MSY for each growth parameter sample
  for (j in 1:n_rep){
    B_MSY_rep[j,h] = B_vec_rep[Index_max[j],j,h]              # B_MSY for each growth parameter sample
    N_MSY_rep[j,h] = N_vec_rep[Index_max[j],j,h]              # N_MSY for each growth parameter sample
    HarvN_MSY_rep[j,h] = HarvN_vec_rep[Index_max[j],j,h]  
    VulnN_MSY_rep[j,h] = VulnN_vec_rep[Index_max[j],j,h]  
    TrophyN_MSY_rep[j,h] = TrophyN_vec_rep[Index_max[j],j,h]
  }
  YNmax_rep[,h] = apply(YN_vec_rep[,,h], 2, max)              # Maximum number of harvested fish for each growth parameter sample
}

#################################
# Plots of output metrices over F
#################################
# Function to provide 25% quantile, mean, and 75 % qantile
MeanIQR <- function(Data){
  c(round(mean(Data),4), round(quantile(Data, prob=.25),4), round(quantile(Data, prob=.75),4) )
}

N_mean_IQR = array(NA, dim=c(n, 3, n_meth))                      # Average stock size (Quantiles and mean for all growth parameter samples)
HarvN_mean_IQR = array(NA, dim=c(n, 3, n_meth))                  # Average harvestable stock size (Quantiles and mean for all growth parameter samples)
VulnN_mean_IQR = array(NA, dim=c(n, 3, n_meth))                  # Average stock size vulnerable to catch (Quantiles and mean for all growth parameter samples)
TrophyN_mean_IQR = array(NA, dim=c(n, 3, n_meth))                # Average trophy stock size (Quantiles and mean for all growth parameter samples)
AmountTrophy_mean_IQR = array(NA, dim=c(n, 3, n_meth))           # Average amount of trophy fish in population (Quantiles and mean for all growth parameter samples)
B_mean_IQR = array(NA, dim=c(n, 3, n_meth))                      # Average stock biomass (Quantiles and mean for all growth parameter samples)
Y_mean_IQR = array(NA, dim=c(n, 3, n_meth))                      # Average yield (Quantiles and mean for all growth parameter samples)
YN_mean_IQR = array(NA, dim=c(n, 3, n_meth))                     # Average numeric yield (Quantiles and mean for all growth parameter samples)

for(h in 1:n_meth){
  for(i in 1:n){
    N_mean_IQR[i,,h] = MeanIQR(N_vec_rep[i,,h])                   # Quantiles and mean of average stock size [ind.]
    HarvN_mean_IQR[i,,h] = MeanIQR(HarvN_vec_rep[i,,h])           # Quantiles and mean of average harvestable stock size [ind.]
    VulnN_mean_IQR[i,,h] = MeanIQR(VulnN_vec_rep[i,,h])           # Quantiles and mean of average harvestable stock size [ind.]
    TrophyN_mean_IQR[i,,h] = MeanIQR(TrophyN_vec_rep[i,,h])       # Quantiles and mean of average trophy stock size [ind.]
    AmountTrophy_mean_IQR[i,,h] = MeanIQR(AmountTrophy_vec_rep[i,,h])       # Quantiles and mean of average amount of trophy fish in population []
    B_mean_IQR[i,,h] = MeanIQR(B_vec_rep[i,,h])                   # Quantiles and mean of average stock biomass [t]
    Y_mean_IQR[i,,h] = MeanIQR(Y_vec_rep[i,,h])                   # Quantiles and mean of average yield [t year^-1]
    YN_mean_IQR[i,,h] = MeanIQR(YN_vec_rep[i,,h])                 # Quantiles and mean of average numeric yield [Ind. year^-1]
  }
}

# Plot settings
ggbg <- function() {                          # for background and grid color of plot
  points(0, 0, pch=16, cex=1e6, col="white")
  grid(col="gray95", lty=1)
}

fontsize_lab = 1.4
fontsize_axis = 1.2
linewidth = 2.0
pointsize = 1.5
Col_data = c("#E69F00", "#56B4E9", "grey35")
Col_IQR = adjustcolor(Col_data, alpha.f = 0.2)
AreaDensLine = c(NA, NA, 35)
AreaAngleLine = c(NA, NA, 90)
subplot_labels = c("a", "b", "c")

# Values and labels of plot axes for two different size limits (x-axis) and three different output metrices (y-axis), respectively
ScalingN = 1e5
Xlab = expression("Fishing mortality [" ~ year^{-1} ~"]")
Yax = c(parse(text="Y_mean_IQR*1e3/Bodden_area"), parse(text="B_mean_IQR*1e3/Bodden_area"), parse(text="AmountTrophy_mean_IQR"))
Ylab = c(expression("Yield [kg" ~ ha^-1 ~ year^{-1} ~ "]"), expression("Biomass [kg" ~ ha^-1 ~ "]"), expression("Amount of fish">="1m"))
#Y_F_MSY = c(parse(text="MSY"), parse(text="B_MSY"), parse(text="TrophyN_MSY"))

# Plotting function - plot output metrics 'Y' (= Yield, Biomass or Number of trophy fish)
Plot_func <- function(x, yax, F_MSY, Xlab, Ylab, panel, Col_data, Col_IQR, AreaDensLine, AreaAngleLine, linewidth, pointsize, fontsize_lab, fontsize_axis, subplot_label, LEGEND){
  # -> Scales - mean and IQR
  matplot(x, yax[,1,1], xlab=Xlab, ylab=Ylab, panel.first=panel, col=Col_data[1], type='l',
          lty=1, lwd=linewidth, cex.lab=fontsize_lab, cex.axis=fontsize_axis, ylim=c(0,max(yax)))
  polygon(c(x, rev(x)), c(yax[,3,1], rev(yax[,2,1])), col=Col_IQR[1], density = AreaDensLine[1], angle = AreaAngleLine[1], border=NA)
  # -> Otoliths - mean and IQR
  points(x, yax[,1,2], type='l',  lty=1, lwd=linewidth, col=Col_data[2])
  polygon(c(x,rev(x)),c(yax[,3,2],rev(yax[,2,2])),col=Col_IQR[2], density = AreaDensLine[2], angle = AreaAngleLine[2], border=NA)
  # -> Corroborated age - mean and IQR
  points(x, yax[,1,3], type='l',  lty=1, lwd=linewidth, col=Col_data[3])
  polygon(c(x,rev(x)),c(yax[,3,3],rev(yax[,2,3])),col=Col_IQR[3], density = AreaDensLine[3], angle = AreaAngleLine[3], border=NA)
  
  # for (nn in 1:3){
  #   segments(F_MSY[nn],0,F_MSY[nn],y_F_MSY[nn],col=Col_data[nn],lty=2)
  #   points(F_MSY[nn],y_F_MSY[nn],col=Col_data[nn],pch=16,cex=pointsize)         # adding reference point for (F_MSY, MSY)
  # }

  mtext(subplot_label, adj=-0.27, line=-0.1)
  
  if(LEGEND==T) { legend("topright",c("Historic", "Recent", "Freshwater"), lty=1, col=Col_data)}
}

# Plotting - min, mean and max of model output (if no cycles, all 3 appearing as one line)
if(SAVE){png("Figures/Curves_YieldBiomTrophy_vs_F.png", width = 6000, height = 1800, res=600)}
par(mfrow=c(1,3),mar=c(4,5,1,1)) #,bty="n")

for(pp in 1:length(Yax)){
  yax = eval(Yax[pp])
  if(pp == 2){LEGEND = T} else{LEGEND = F}
  Plot_func(F_mort_vec, yax, F_MSY[1,], Xlab, Ylab[pp], ggbg(), Col_data, Col_IQR, AreaDensLine, AreaAngleLine, linewidth, pointsize, fontsize_lab, fontsize_axis, subplot_labels[pp], LEGEND)
}

if(SAVE){dev.off()}
```


